<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Spatial Data Science in R</title>
  <meta name="description" content="Lessons and tasks from GIS courses by Jonathan Jupke" />
  <meta name="generator" content="bookdown 0.41 and GitBook 2.6.7" />

  <meta property="og:title" content="Spatial Data Science in R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Lessons and tasks from GIS courses by Jonathan Jupke" />
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Spatial Data Science in R" />
  
  <meta name="twitter:description" content="Lessons and tasks from GIS courses by Jonathan Jupke" />
  

<meta name="author" content="Jonathan Jupke" />


<meta name="date" content="2024-11-18" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  

<link rel="next" href="rasters-in-r-the-terra-package.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/leaflet-1.3.1/leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-1.3.1/leaflet.js"></script>
<link href="libs/leafletfix-1.0.0/leafletfix.css" rel="stylesheet" />
<script src="libs/proj4-2.6.2/proj4.min.js"></script>
<script src="libs/Proj4Leaflet-1.0.1/proj4leaflet.js"></script>
<link href="libs/rstudio_leaflet-1.3.1/rstudio_leaflet.css" rel="stylesheet" />
<script src="libs/leaflet-binding-2.2.2/leaflet.js"></script>
<script src="libs/leaflet-providers-2.0.0/leaflet-providers_2.0.0.js"></script>
<script src="libs/leaflet-providers-plugin-2.2.2/leaflet-providers-plugin.js"></script>
<link href="libs/HomeButton-0.0.1/home-button.css" rel="stylesheet" />
<script src="libs/HomeButton-0.0.1/home-button.js"></script>
<script src="libs/HomeButton-0.0.1/easy-button-src.min.js"></script>
<script src="libs/clipboard-0.0.1/setClipboardText.js"></script>
<link href="libs/mapviewCSS-0.0.1/mapview-popup.css" rel="stylesheet" />
<link href="libs/mapviewCSS-0.0.1/mapview.css" rel="stylesheet" />


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>
<style type="text/css">
/* Used with Pandoc 2.11+ new --citeproc when CSL is used */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Spatial Data Science in R</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html"><i class="fa fa-check"></i><b>1</b> Introduction to the sf package</a>
<ul>
<li class="chapter" data-level="1.1" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#loading-spatial-data-into-r"><i class="fa fa-check"></i><b>1.1</b> Loading spatial data into R</a></li>
<li class="chapter" data-level="1.2" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#creating-spatial-data-yourself"><i class="fa fa-check"></i><b>1.2</b> Creating spatial data yourself</a></li>
<li class="chapter" data-level="1.3" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#basic-operations"><i class="fa fa-check"></i><b>1.3</b> Basic operations</a></li>
<li class="chapter" data-level="1.4" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#useful-functions"><i class="fa fa-check"></i><b>1.4</b> Useful functions</a>
<ul>
<li class="chapter" data-level="1.4.1" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#st_area"><i class="fa fa-check"></i><b>1.4.1</b> <code>st_area</code></a></li>
<li class="chapter" data-level="1.4.2" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#st_bbox"><i class="fa fa-check"></i><b>1.4.2</b> <code>st_bbox()</code></a></li>
<li class="chapter" data-level="1.4.3" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#st_buffer"><i class="fa fa-check"></i><b>1.4.3</b> <code>st_buffer()</code></a></li>
<li class="chapter" data-level="1.4.4" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#st_coordinates"><i class="fa fa-check"></i><b>1.4.4</b> <code>st_coordinates()</code></a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#geometric-set-operations"><i class="fa fa-check"></i><b>1.5</b> Geometric set operations</a>
<ul>
<li class="chapter" data-level="1.5.1" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#st_distance"><i class="fa fa-check"></i><b>1.5.1</b> <code>st_distance</code></a></li>
<li class="chapter" data-level="1.5.2" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#st_nearest_feature"><i class="fa fa-check"></i><b>1.5.2</b> <code>st_nearest_feature</code></a></li>
<li class="chapter" data-level="1.5.3" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#spatial-subsetting"><i class="fa fa-check"></i><b>1.5.3</b> spatial subsetting</a></li>
<li class="chapter" data-level="1.5.4" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#spatial-joins"><i class="fa fa-check"></i><b>1.5.4</b> spatial joins</a></li>
<li class="chapter" data-level="1.5.5" data-path="introduction-to-the-sf-package.html"><a href="introduction-to-the-sf-package.html#spatial-sggregation"><i class="fa fa-check"></i><b>1.5.5</b> spatial sggregation</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="2" data-path="rasters-in-r-the-terra-package.html"><a href="rasters-in-r-the-terra-package.html"><i class="fa fa-check"></i><b>2</b> Rasters in R: The terra package</a>
<ul>
<li class="chapter" data-level="2.1" data-path="rasters-in-r-the-terra-package.html"><a href="rasters-in-r-the-terra-package.html#basic-idea"><i class="fa fa-check"></i><b>2.1</b> Basic idea</a></li>
<li class="chapter" data-level="2.2" data-path="rasters-in-r-the-terra-package.html"><a href="rasters-in-r-the-terra-package.html#creating-a-new-raster"><i class="fa fa-check"></i><b>2.2</b> Creating a new Raster</a></li>
<li class="chapter" data-level="2.3" data-path="rasters-in-r-the-terra-package.html"><a href="rasters-in-r-the-terra-package.html#going-beyond-the-hull"><i class="fa fa-check"></i><b>2.3</b> Going beyond the hull</a></li>
<li class="chapter" data-level="2.4" data-path="rasters-in-r-the-terra-package.html"><a href="rasters-in-r-the-terra-package.html#multiple-layers-in-one-spatraster"><i class="fa fa-check"></i><b>2.4</b> Multiple layers in one SpatRaster</a></li>
<li class="chapter" data-level="2.5" data-path="rasters-in-r-the-terra-package.html"><a href="rasters-in-r-the-terra-package.html#raster-algebra"><i class="fa fa-check"></i><b>2.5</b> Raster algebra</a></li>
<li class="chapter" data-level="2.6" data-path="rasters-in-r-the-terra-package.html"><a href="rasters-in-r-the-terra-package.html#high-level-functions"><i class="fa fa-check"></i><b>2.6</b> High-level functions</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="rasters-in-r-the-terra-package.html"><a href="rasters-in-r-the-terra-package.html#extracting-raster-values-with-vectors"><i class="fa fa-check"></i><b>2.6.1</b> Extracting raster values with vectors</a></li>
<li class="chapter" data-level="2.6.2" data-path="rasters-in-r-the-terra-package.html"><a href="rasters-in-r-the-terra-package.html#masking"><i class="fa fa-check"></i><b>2.6.2</b> Masking</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="rasters-in-r-the-terra-package.html"><a href="rasters-in-r-the-terra-package.html#cell-level-functions"><i class="fa fa-check"></i><b>2.7</b> Cell-level functions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="point-pattern-analysis.html"><a href="point-pattern-analysis.html"><i class="fa fa-check"></i><b>3</b> Point Pattern Analysis</a>
<ul>
<li class="chapter" data-level="3.1" data-path="point-pattern-analysis.html"><a href="point-pattern-analysis.html#the-ppp-class"><i class="fa fa-check"></i><b>3.1</b> the ppp class</a></li>
<li class="chapter" data-level="3.2" data-path="point-pattern-analysis.html"><a href="point-pattern-analysis.html#first-order-processes"><i class="fa fa-check"></i><b>3.2</b> First order processes</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="point-pattern-analysis.html"><a href="point-pattern-analysis.html#kernel-density"><i class="fa fa-check"></i><b>3.2.1</b> Kernel density</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="point-pattern-analysis.html"><a href="point-pattern-analysis.html#second-order-processes"><i class="fa fa-check"></i><b>3.3</b> Second order processes</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="point-pattern-analysis.html"><a href="point-pattern-analysis.html#average-nearest-neighbor"><i class="fa fa-check"></i><b>3.3.1</b> Average nearest neighbor</a></li>
<li class="chapter" data-level="3.3.2" data-path="point-pattern-analysis.html"><a href="point-pattern-analysis.html#the-k-funktion"><i class="fa fa-check"></i><b>3.3.2</b> The K-Funktion</a></li>
<li class="chapter" data-level="3.3.3" data-path="point-pattern-analysis.html"><a href="point-pattern-analysis.html#morans-i"><i class="fa fa-check"></i><b>3.3.3</b> Morans I</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="interpolation.html"><a href="interpolation.html"><i class="fa fa-check"></i><b>4</b> Interpolation</a>
<ul>
<li class="chapter" data-level="4.1" data-path="interpolation.html"><a href="interpolation.html#the-data"><i class="fa fa-check"></i><b>4.1</b> The data</a></li>
<li class="chapter" data-level="4.2" data-path="interpolation.html"><a href="interpolation.html#proximity-polygons"><i class="fa fa-check"></i><b>4.2</b> Proximity Polygons</a></li>
<li class="chapter" data-level="4.3" data-path="interpolation.html"><a href="interpolation.html#trend-surface-analysis"><i class="fa fa-check"></i><b>4.3</b> Trend Surface Analysis</a></li>
<li class="chapter" data-level="4.4" data-path="interpolation.html"><a href="interpolation.html#splines"><i class="fa fa-check"></i><b>4.4</b> Splines</a></li>
<li class="chapter" data-level="4.5" data-path="interpolation.html"><a href="interpolation.html#weighted-averaging"><i class="fa fa-check"></i><b>4.5</b> Weighted averaging</a></li>
<li class="chapter" data-level="4.6" data-path="interpolation.html"><a href="interpolation.html#kriging"><i class="fa fa-check"></i><b>4.6</b> Kriging</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="machine-learning.html"><a href="machine-learning.html"><i class="fa fa-check"></i><b>5</b> Machine Learning</a>
<ul>
<li class="chapter" data-level="5.1" data-path="machine-learning.html"><a href="machine-learning.html#terrain-analysis-with-terra"><i class="fa fa-check"></i><b>5.1</b> Terrain analysis with terra</a></li>
<li class="chapter" data-level="5.2" data-path="machine-learning.html"><a href="machine-learning.html#ploting-the-data"><i class="fa fa-check"></i><b>5.2</b> Ploting the data</a></li>
<li class="chapter" data-level="5.3" data-path="machine-learning.html"><a href="machine-learning.html#logistic-regression"><i class="fa fa-check"></i><b>5.3</b> Logistic regression</a></li>
<li class="chapter" data-level="5.4" data-path="machine-learning.html"><a href="machine-learning.html#mlr3"><i class="fa fa-check"></i><b>5.4</b> mlr3</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="machine-learning.html"><a href="machine-learning.html#creating-a-task"><i class="fa fa-check"></i><b>5.4.1</b> Creating a <em>task</em></a></li>
<li class="chapter" data-level="5.4.2" data-path="machine-learning.html"><a href="machine-learning.html#the-learner"><i class="fa fa-check"></i><b>5.4.2</b> The <em>learner</em></a></li>
<li class="chapter" data-level="5.4.3" data-path="machine-learning.html"><a href="machine-learning.html#hyperparameter-tuning"><i class="fa fa-check"></i><b>5.4.3</b> Hyperparameter Tuning</a></li>
<li class="chapter" data-level="5.4.4" data-path="machine-learning.html"><a href="machine-learning.html#predictions"><i class="fa fa-check"></i><b>5.4.4</b> Predictions</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="graph-analysis.html"><a href="graph-analysis.html"><i class="fa fa-check"></i><b>6</b> Graph Analysis</a>
<ul>
<li class="chapter" data-level="6.1" data-path="graph-analysis.html"><a href="graph-analysis.html#the-igraph-package"><i class="fa fa-check"></i><b>6.1</b> The igraph package</a></li>
<li class="chapter" data-level="6.2" data-path="graph-analysis.html"><a href="graph-analysis.html#from-data-to-graph"><i class="fa fa-check"></i><b>6.2</b> From data to graph</a></li>
<li class="chapter" data-level="6.3" data-path="graph-analysis.html"><a href="graph-analysis.html#centrality-measures"><i class="fa fa-check"></i><b>6.3</b> Centrality measures</a></li>
<li class="chapter" data-level="6.4" data-path="graph-analysis.html"><a href="graph-analysis.html#visualization"><i class="fa fa-check"></i><b>6.4</b> Visualization</a></li>
<li class="chapter" data-level="6.5" data-path="graph-analysis.html"><a href="graph-analysis.html#network-models"><i class="fa fa-check"></i><b>6.5</b> Network Models</a></li>
<li class="chapter" data-level="6.6" data-path="graph-analysis.html"><a href="graph-analysis.html#optimal-channel-networks"><i class="fa fa-check"></i><b>6.6</b> Optimal Channel Networks</a></li>
<li class="chapter" data-level="6.7" data-path="graph-analysis.html"><a href="graph-analysis.html#sfnetworks"><i class="fa fa-check"></i><b>6.7</b> sfnetworks</a>
<ul>
<li class="chapter" data-level="6.7.1" data-path="graph-analysis.html"><a href="graph-analysis.html#finding-paths-in-the-network"><i class="fa fa-check"></i><b>6.7.1</b> Finding paths in the network</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html"><i class="fa fa-check"></i><b>7</b> Creating Maps in R</a>
<ul>
<li class="chapter" data-level="7.1" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#tmap"><i class="fa fa-check"></i><b>7.1</b> tmap</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#basic-tmaps"><i class="fa fa-check"></i><b>7.1.1</b> Basic tmaps</a></li>
<li class="chapter" data-level="7.1.2" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#adjusting-visual-elements-and-multiple-groups"><i class="fa fa-check"></i><b>7.1.2</b> Adjusting visual elements and multiple groups</a></li>
<li class="chapter" data-level="7.1.3" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#map-extend"><i class="fa fa-check"></i><b>7.1.3</b> Map extend</a></li>
<li class="chapter" data-level="7.1.4" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#further-map-elements"><i class="fa fa-check"></i><b>7.1.4</b> Further map elements</a></li>
<li class="chapter" data-level="7.1.5" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#making-the-map-prettier"><i class="fa fa-check"></i><b>7.1.5</b> Making the map prettier</a></li>
<li class="chapter" data-level="7.1.6" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#save-to-maps-to-file"><i class="fa fa-check"></i><b>7.1.6</b> Save to maps to file</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#rastervis"><i class="fa fa-check"></i><b>7.2</b> rasterVis</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#beyond-the-usual"><i class="fa fa-check"></i><b>7.2.1</b> Beyond the usual</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#cartographer"><i class="fa fa-check"></i><b>7.3</b> Cartographer</a></li>
<li class="chapter" data-level="7.4" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#rayshader"><i class="fa fa-check"></i><b>7.4</b> Rayshader</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="creating-maps-in-r.html"><a href="creating-maps-in-r.html#setup"><i class="fa fa-check"></i><b>7.4.1</b> Setup</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="8" data-path="where-do-i-get-data.html"><a href="where-do-i-get-data.html"><i class="fa fa-check"></i><b>8</b> Where do I get data❓</a>
<ul>
<li class="chapter" data-level="8.1" data-path="where-do-i-get-data.html"><a href="where-do-i-get-data.html#websites"><i class="fa fa-check"></i><b>8.1</b> Websites</a></li>
<li class="chapter" data-level="8.2" data-path="where-do-i-get-data.html"><a href="where-do-i-get-data.html#packages"><i class="fa fa-check"></i><b>8.2</b> Packages</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="where-do-i-get-data.html"><a href="where-do-i-get-data.html#geodata"><i class="fa fa-check"></i><b>8.2.1</b> geodata</a></li>
<li class="chapter" data-level="8.2.2" data-path="where-do-i-get-data.html"><a href="where-do-i-get-data.html#osmdata"><i class="fa fa-check"></i><b>8.2.2</b> osmdata</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="usefull-packages.html"><a href="usefull-packages.html"><i class="fa fa-check"></i><b>9</b> Usefull packages</a>
<ul>
<li class="chapter" data-level="9.1" data-path="usefull-packages.html"><a href="usefull-packages.html#coordinatecleaner"><i class="fa fa-check"></i><b>9.1</b> ‘CoordinateCleaner’</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i><b>10</b> References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Spatial Data Science in R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="header">
<h1 class="title">Spatial Data Science in R</h1>
<p class="author"><em>Jonathan Jupke</em></p>
<p class="date"><em>2024-11-18</em></p>
</div>
<div id="introduction-to-the-sf-package" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Chapter 1</span> Introduction to the sf package<a href="introduction-to-the-sf-package.html#introduction-to-the-sf-package" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>The most common way to handle spatial data in R is with the <code>sf</code> package <span class="citation">(<a href="#ref-pebesmaSimpleFeaturesStandardized2018">Pebesma 2018</a>)</span>.
In this first chapter, you will learn the basics of <code>sf</code> - everything you need to load, visualize, alter, and analyze spatial data in R.
If you are looking more comprehensive introduction to <code>sf</code> and some additional packages, a great and free resource are the books <em>Geocomputation in R</em> <span class="citation">(<a href="#ref-Lovelace2019">Lovelace, Nowosad, and Muenchow 2019</a>)</span> available <a href="https://geocompr.robinlovelace.net/">here</a> and <em>Spatial Data Science</em> <span class="citation">(<a href="#ref-Pebesma2022">Pebesma and Bivand 2022</a>)</span> available <a href="https://r-spatial.org/book/">here</a>.</p>
<div id="loading-spatial-data-into-r" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Loading spatial data into R<a href="introduction-to-the-sf-package.html#loading-spatial-data-into-r" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>First we need to install and load the <code>sf</code> package.
You only need to install the package once with</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="introduction-to-the-sf-package.html#cb1-1" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">&quot;sf&quot;</span>)</span></code></pre></div>
<p>When the package is already installed. You can use <code>library()</code> or <code>require()</code> to load it.
For you purposes, it makes no difference which of the two functions you use.
You need to load the package at the start of each new R session, so every time you start R.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="introduction-to-the-sf-package.html#cb2-1" tabindex="-1"></a><span class="fu">library</span>(sf)</span></code></pre></div>
<pre><code>## Linking to GEOS 3.12.1, GDAL 3.8.4, PROJ 9.3.1; sf_use_s2() is TRUE</code></pre>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.1</strong></p>
</div>
<ul>
<li>Install and load the sf R package</li>
</ul>
</div>
<p><br/></p>
<p><code>sf</code> establishes a connection between the running R instance and three other programs: GEOS, GDAL and PROJ.
<a href="https://libgeos.org/">GEOS</a> and <a href="https://gdal.org/">GDAL</a> are collections of functions to read, modify, and write geodata; <a href="https://proj.org/">PROJ</a> transforms geodata from one coordinate reference system to another.</p>
<p>Next, we want to load files into R.
Before we can do that, you need to set your working directory.
A working directory in R is the default location on your computer where R will look for files to read and where it will save files you create. It’s essentially the main folder R is operating in during your current session. You can check your current working directory using the <code>getwd()</code> function and change it using <code>setwd()</code>.
Below, I set my working directory.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="introduction-to-the-sf-package.html#cb4-1" tabindex="-1"></a><span class="fu">setwd</span>(<span class="st">&quot;~/Uni/teaching/GIS/&quot;</span>)</span></code></pre></div>
<p>You have to adjust the working directory to your folder structure.
There are some tricks and rules to defining a path in R.
Once you have written the quotation marks (““) and place your cursor between them, you can summon a list of all folders in the current working directory by hitting the tabulator key.
By default any path you enter is relative to your current working directory.
If you want to go back to the root directory of your computer start with the tilde (<code>"~"</code>) as I did above.
If instead, you want to use a relative path, and need to go higher in the folder structure, use <code>"../"</code>.<br />
If you are not sure how to write the path to your desired folder you can use the <code>file.choose()</code> function.
After executing the function a window prompt will open where you can select the desired folder in a point-and-click fashion.
In the function you have to choose a file by double-clicking it.
R will now print the path to the selected file in the console.
The argument to <code>setwd()</code> needs to be the path to a folder.
Therefore, to use the path <code>file.choose()</code> provided you need to remove the file name from the path.</p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.2</strong></p>
</div>
<ul>
<li>Create a folder where you will store all your files for this class<br />
</li>
<li>Set the working directory to that folder</li>
</ul>
</div>
<p><br/></p>
<p>With the command <code>st_read()</code>, we read the geopackage file <code>gadm36_DEU_3_pk.gpkg</code> (download <a href="https://seafile.rlp.net/f/28b46dd2c13a43958a6d/?dl=1">here</a>).
The function starts, like all functions in <code>sf</code>, with <code>st_</code>, short for <em>spatiotemporal</em>.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="introduction-to-the-sf-package.html#cb5-1" tabindex="-1"></a>germany <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">&quot;data/gadm36_DEU_3_pk.gpkg&quot;</span>)</span></code></pre></div>
<pre><code>## Reading layer `gadm36_DEU_3_pk&#39; from data source `C:\Users\jonat\Documents\001_Uni\002_teaching\online books\book_spatial_data_science_in_R\data\gadm36_DEU_3_pk.gpkg&#39; using driver `GPKG&#39;
## Simple feature collection with 4680 features and 16 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 5.866251 ymin: 47.27012 xmax: 15.04181 ymax: 55.05653
## Geodetic CRS:  WGS 84</code></pre>
<p>After the file is loaded, we automatically get a set of information.</p>
<p><img src="images/sf-load_data.png" alt="R Output after loading gadm36_DEU_3_pk.gpkg" />
<br/></p>
<p>These are from left to right and top to bottom following the yellow boxes: The layer name of the loaded file. This is not the object name in R, but the name stored in the geopackage (gpkg) file; where the file is located on disk; the file format (here GPKG); the number of rows (<em>features</em>, 4680) and columns (<em>fields</em>, 16); the feature type (GeometryType); the bounding box, i.e., minimum and maximum x and y coordinate data or longitude and latitude, and finally the coordinate reference system.</p>
<p>If we now open the object in R, we see the following:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="introduction-to-the-sf-package.html#cb7-1" tabindex="-1"></a>germany</span></code></pre></div>
<pre><code>## Simple feature collection with 4680 features and 16 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 5.866251 ymin: 47.27012 xmax: 15.04181 ymax: 55.05653
## Geodetic CRS:  WGS 84
## First 10 features:
##    GID_0  NAME_0   GID_1            NAME_1 NL_NAME_1     GID_2          NAME_2 NL_NAME_2        GID_3                NAME_3 VARNAME_3 NL_NAME_3                  TYPE_3    ENGTYPE_3
## 1    DEU Germany DEU.1_1 Baden-Württemberg      &lt;NA&gt; DEU.1.1_1 Alb-Donau-Kreis      &lt;NA&gt;  DEU.1.1.1_1          Allmendingen      &lt;NA&gt;      &lt;NA&gt; Verwaltungsgemeinschaft Municipality
## 2    DEU Germany DEU.1_1 Baden-Württemberg      &lt;NA&gt; DEU.1.1_1 Alb-Donau-Kreis      &lt;NA&gt;  DEU.1.1.2_1            Blaubeuren      &lt;NA&gt;      &lt;NA&gt; Verwaltungsgemeinschaft Municipality
## 3    DEU Germany DEU.1_1 Baden-Württemberg      &lt;NA&gt; DEU.1.1_1 Alb-Donau-Kreis      &lt;NA&gt;  DEU.1.1.3_1             Blaustein      &lt;NA&gt;      &lt;NA&gt;        Einheitsgemeinde Municipality
## 4    DEU Germany DEU.1_1 Baden-Württemberg      &lt;NA&gt; DEU.1.1_1 Alb-Donau-Kreis      &lt;NA&gt;  DEU.1.1.4_1            Dietenheim      &lt;NA&gt;      &lt;NA&gt;      Verwaltungsverband Municipality
## 5    DEU Germany DEU.1_1 Baden-Württemberg      &lt;NA&gt; DEU.1.1_1 Alb-Donau-Kreis      &lt;NA&gt;  DEU.1.1.5_1             Dornstadt      &lt;NA&gt;      &lt;NA&gt; Verwaltungsgemeinschaft Municipality
## 6    DEU Germany DEU.1_1 Baden-Württemberg      &lt;NA&gt; DEU.1.1_1 Alb-Donau-Kreis      &lt;NA&gt;  DEU.1.1.6_1       Ehingen (Donau)      &lt;NA&gt;      &lt;NA&gt; Verwaltungsgemeinschaft Municipality
## 7    DEU Germany DEU.1_1 Baden-Württemberg      &lt;NA&gt; DEU.1.1_1 Alb-Donau-Kreis      &lt;NA&gt;  DEU.1.1.7_1                Erbach      &lt;NA&gt;      &lt;NA&gt;        Einheitsgemeinde Municipality
## 8    DEU Germany DEU.1_1 Baden-Württemberg      &lt;NA&gt; DEU.1.1_1 Alb-Donau-Kreis      &lt;NA&gt;  DEU.1.1.8_1 Kirchberg-Weihungstal      &lt;NA&gt;      &lt;NA&gt;      Verwaltungsverband Municipality
## 9    DEU Germany DEU.1_1 Baden-Württemberg      &lt;NA&gt; DEU.1.1_1 Alb-Donau-Kreis      &lt;NA&gt;  DEU.1.1.9_1        Laichinger Alb      &lt;NA&gt;      &lt;NA&gt;      Verwaltungsverband Municipality
## 10   DEU Germany DEU.1_1 Baden-Württemberg      &lt;NA&gt; DEU.1.1_1 Alb-Donau-Kreis      &lt;NA&gt; DEU.1.1.10_1              Langenau      &lt;NA&gt;      &lt;NA&gt;      Verwaltungsverband Municipality
##         CC_3 HASC_3                           geom
## 1  084255001   &lt;NA&gt; MULTIPOLYGON (((9.777709 48...
## 2  084255002   &lt;NA&gt; MULTIPOLYGON (((9.775818 48...
## 3  084250141   &lt;NA&gt; MULTIPOLYGON (((9.827528 48...
## 4  084255003   &lt;NA&gt; MULTIPOLYGON (((10.00971 48...
## 5  084255004   &lt;NA&gt; MULTIPOLYGON (((9.972806 48...
## 6  084255005   &lt;NA&gt; MULTIPOLYGON (((9.803958 48...
## 7  084250039   &lt;NA&gt; MULTIPOLYGON (((9.837822 48...
## 8  084255006   &lt;NA&gt; MULTIPOLYGON (((10.02729 48...
## 9  084255007   &lt;NA&gt; MULTIPOLYGON (((9.708008 48...
## 10 084255008   &lt;NA&gt; MULTIPOLYGON (((9.946911 48...</code></pre>
<p><br/></p>
<p>The header is similar to what we have already seen when reading the file. Below are the first ten rows and all columns.
The object has the classes:</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="introduction-to-the-sf-package.html#cb9-1" tabindex="-1"></a><span class="fu">class</span>(germany)</span></code></pre></div>
<pre><code>## [1] &quot;sf&quot;         &quot;data.frame&quot;</code></pre>
<p>For the most part, we can handle sf objects like normal data frames.
We can use the <code>[</code> subsetting operations.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="introduction-to-the-sf-package.html#cb11-1" tabindex="-1"></a>germany[,<span class="dv">1</span>]</span></code></pre></div>
<pre><code>## Simple feature collection with 4680 features and 1 field
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 5.866251 ymin: 47.27012 xmax: 15.04181 ymax: 55.05653
## Geodetic CRS:  WGS 84
## First 10 features:
##    GID_0                           geom
## 1    DEU MULTIPOLYGON (((9.777709 48...
## 2    DEU MULTIPOLYGON (((9.775818 48...
## 3    DEU MULTIPOLYGON (((9.827528 48...
## 4    DEU MULTIPOLYGON (((10.00971 48...
## 5    DEU MULTIPOLYGON (((9.972806 48...
## 6    DEU MULTIPOLYGON (((9.803958 48...
## 7    DEU MULTIPOLYGON (((9.837822 48...
## 8    DEU MULTIPOLYGON (((10.02729 48...
## 9    DEU MULTIPOLYGON (((9.708008 48...
## 10   DEU MULTIPOLYGON (((9.946911 48...</code></pre>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="introduction-to-the-sf-package.html#cb13-1" tabindex="-1"></a>germany[<span class="dv">1</span>,]</span></code></pre></div>
<pre><code>## Simple feature collection with 1 feature and 16 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 9.61846 ymin: 48.29861 xmax: 9.822202 ymax: 48.36533
## Geodetic CRS:  WGS 84
##   GID_0  NAME_0   GID_1            NAME_1 NL_NAME_1     GID_2          NAME_2 NL_NAME_2       GID_3       NAME_3 VARNAME_3 NL_NAME_3                  TYPE_3    ENGTYPE_3      CC_3
## 1   DEU Germany DEU.1_1 Baden-Württemberg      &lt;NA&gt; DEU.1.1_1 Alb-Donau-Kreis      &lt;NA&gt; DEU.1.1.1_1 Allmendingen      &lt;NA&gt;      &lt;NA&gt; Verwaltungsgemeinschaft Municipality 084255001
##   HASC_3                           geom
## 1   &lt;NA&gt; MULTIPOLYGON (((9.777709 48...</code></pre>
<p><br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.3</strong></p>
</div>
<ul>
<li>Read the germany data into R<br />
</li>
<li>Create a subset that only contains the first 10 rows<br />
</li>
<li>Create a subset that only contains the last 10 rows<br />
</li>
<li>Create a subset that only contains the columns: “NAME_3”, “TYPE_3”, and geom.</li>
</ul>
</div>
<p><br/></p>
<p>However, when we subset the columns of an sf object, we always keep the <code>geom</code> or <code>geometry</code> column.
Usually, this is convenient because this column contains the spatial coordinates of the objects.
Because it is not removed in these selection operations, the <code>geom</code> column is a so-called <em>sticky</em> column.
However, if you want to remove this column explicitly, you can use <code>st_drop_geometry()</code>.
The <code>geom</code> column is different in another way - it is a <a href="https://adv-r.hadley.nz/vectors-chap.html#list-columns">list column</a>.
Unlike other columns that are vectors, it is a list, which means that it can store different kinds of data or multiple entries in a single cell.
This makes sense, as the geometry column needs to store the coordinates for all points of a multi point, line, or polygon.
The <code>geom</code> column has the class <code>sfc</code>.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="introduction-to-the-sf-package.html#cb15-1" tabindex="-1"></a><span class="fu">class</span>(germany<span class="sc">$</span>geom)</span></code></pre></div>
<pre><code>## [1] &quot;sfc_MULTIPOLYGON&quot; &quot;sfc&quot;</code></pre>
<p><code>sfc</code> is short for <em>simple feature column</em>, i.e., a column for simple features.
The individual elements in the column have the class <code>sfg</code>, <em>simple feature geometry</em>.
<code>sfg</code> are the individual geometric shapes (points, lines, polygons, …).
Below, we will create <code>sfg</code> objects ourselves and compose an <code>sf</code> object from them.</p>
<p>An object of class <code>sf</code> can be visualized with <code>plot()</code>.
For this plot, I subset the data set to the first ten rows and three columns.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="introduction-to-the-sf-package.html#cb17-1" tabindex="-1"></a><span class="fu">plot</span>(germany[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>,<span class="dv">7</span><span class="sc">:</span><span class="dv">9</span>])</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-9-1.png" width="672" />
<br/></p>
<p>As you can see, by default each variable is plotted individually.
Plots with single variables are created when we subset the dataset to one variable.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="introduction-to-the-sf-package.html#cb18-1" tabindex="-1"></a><span class="fu">plot</span>(germany[,<span class="st">&quot;GID_3&quot;</span>])</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-10-1.png" width="672" />
<br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.4</strong></p>
</div>
<ul>
<li>Plot the variable <code>NAME_2</code></li>
</ul>
</div>
<p><br/></p>
</div>
<div id="creating-spatial-data-yourself" class="section level2 hasAnchor" number="1.2">
<h2><span class="header-section-number">1.2</span> Creating spatial data yourself<a href="introduction-to-the-sf-package.html#creating-spatial-data-yourself" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="float">
<img src="images/sf_geometry_type_diagram.png" alt="Relationship of sf geometries (aus Lovelace et al 2021)" />
<div class="figcaption">Relationship of sf geometries (aus Lovelace et al 2021)</div>
</div>
<p>In <code>sf</code>, we can create spatial objects ourselves.
This is rarely necessary since we usually work with data that was created in other projects, but later procedures are easier to understand once you have gone through the process from the beginning. The functions to create geometric shapes follow a simple rule: <code>st_</code> + name of the <em>geometryType</em>. So to create a point we use:</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="introduction-to-the-sf-package.html#cb19-1" tabindex="-1"></a>point1 <span class="ot">&lt;-</span> <span class="fu">st_point</span>(<span class="at">x =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>))</span></code></pre></div>
<p><code>point1</code> is a point with coordinates <code>1 1</code> and has the classes , <code>XY</code>, <code>POINT</code>, and <code>sfg</code>.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="introduction-to-the-sf-package.html#cb20-1" tabindex="-1"></a><span class="fu">class</span>(point1)</span></code></pre></div>
<pre><code>## [1] &quot;XY&quot;    &quot;POINT&quot; &quot;sfg&quot;</code></pre>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="introduction-to-the-sf-package.html#cb22-1" tabindex="-1"></a><span class="fu">plot</span>(point1)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-13-1.png" width="672" />
<br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.5</strong></p>
</div>
<p>Create a point with the coordinates 3 5</p>
</div>
<p><br/></p>
<p>Lines consist of several coordinates which are connected with each other.
The single coordinates are vectors (<code>c()</code>) just like <code>st_point()</code>.
We could use lists, matrices, or data.frames to <code>st_linestring()</code> with several point coordinates.
The easiest way is to use matrices with two columns (one for X and one for Y coordinates) and as many rows as coordinate pairs.
In the example we create a line with the coordinates <code>1 1, 1 2, 2 2, 2 3</code>.
The function <code>matrix()</code> creates a matrix, similar to a data.frame but all columns have the same class, so everything is numeric, character, or boolean. With the <code>data</code> argument we tell R what values this matrix should hold. With <code>ncol = 2</code>, we determine that the matrix will have two columns, and with <code>byrow</code> we establish, that the values will be put into the matrix row-by-row instead of column-by-column. By default, matrices in R are filled column by column, not row by row.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="introduction-to-the-sf-package.html#cb23-1" tabindex="-1"></a>line_coordinates <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">data =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">2</span>,<span class="dv">3</span>), <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">byrow =</span> T)</span></code></pre></div>
<p>Let’s have a look at this matrix.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="introduction-to-the-sf-package.html#cb24-1" tabindex="-1"></a>line_coordinates</span></code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    1
## [2,]    1    2
## [3,]    2    2
## [4,]    2    3</code></pre>
<p>Now, we can turn this into a line with <code>st_linestring</code> and plot it with <code>plot()</code>.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="introduction-to-the-sf-package.html#cb26-1" tabindex="-1"></a>line1 <span class="ot">&lt;-</span> <span class="fu">st_linestring</span>(line_coordinates)</span>
<span id="cb26-2"><a href="introduction-to-the-sf-package.html#cb26-2" tabindex="-1"></a><span class="fu">plot</span>(line1)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>This works but I find the coordinates hard to read in the call to <code>matrix()</code>. It is not instantly clear which values form a pair, especially if the matrix would be larger. Below, I will show an easy-to-read approach.
We create single vectors (<code>c()</code>) with the coordinates for each point and provide these vectors as argument to the <code>rbind()</code> function. The function <code>rbind()</code> (short for <em>row bind</em>) takes single vectors and combines them as rows of a matrix.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="introduction-to-the-sf-package.html#cb27-1" tabindex="-1"></a>line_coordinates <span class="ot">&lt;-</span> </span>
<span id="cb27-2"><a href="introduction-to-the-sf-package.html#cb27-2" tabindex="-1"></a>        <span class="fu">rbind</span>(</span>
<span id="cb27-3"><a href="introduction-to-the-sf-package.html#cb27-3" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), </span>
<span id="cb27-4"><a href="introduction-to-the-sf-package.html#cb27-4" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), </span>
<span id="cb27-5"><a href="introduction-to-the-sf-package.html#cb27-5" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>),</span>
<span id="cb27-6"><a href="introduction-to-the-sf-package.html#cb27-6" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">3</span>)</span>
<span id="cb27-7"><a href="introduction-to-the-sf-package.html#cb27-7" tabindex="-1"></a>        )</span>
<span id="cb27-8"><a href="introduction-to-the-sf-package.html#cb27-8" tabindex="-1"></a>line1 <span class="ot">&lt;-</span> <span class="fu">st_linestring</span>(line_coordinates)</span>
<span id="cb27-9"><a href="introduction-to-the-sf-package.html#cb27-9" tabindex="-1"></a><span class="fu">plot</span>(line1)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-17-1.png" width="672" />
<br/></p>
<p>As you can see, the result is the same, but the single coordinates are not in one long vector.</p>
<p>The equivalent function for columns is called <code>cbind()</code> (<em>column bind</em>).</p>
<p>With the object <code>line_coordinates</code>, we can also create a <em>multipoint</em>.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="introduction-to-the-sf-package.html#cb28-1" tabindex="-1"></a>multipoint1 <span class="ot">&lt;-</span> <span class="fu">st_multipoint</span>(line_coordinates)</span>
<span id="cb28-2"><a href="introduction-to-the-sf-package.html#cb28-2" tabindex="-1"></a><span class="fu">plot</span>(multipoint1)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-18-1.png" width="672" />
<br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.6</strong></p>
</div>
<ul>
<li>Create a line with the coordinates 00 01 02 03 14 24 34 44</li>
</ul>
</div>
<p><br/></p>
<p>When we have a single polygon it looks like a <em>LineString</em> with the difference that the first coordinate pair and the last are the same. Also note that the argument to <code>st_polygon()</code> needs to be a list. So we additionally wrap <code>polygon_coordinates</code> in a call to <code>list()</code> within our call to <code>st_polygon()</code>.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="introduction-to-the-sf-package.html#cb29-1" tabindex="-1"></a>polygon_coordinates <span class="ot">&lt;-</span> </span>
<span id="cb29-2"><a href="introduction-to-the-sf-package.html#cb29-2" tabindex="-1"></a>        <span class="fu">rbind</span>(</span>
<span id="cb29-3"><a href="introduction-to-the-sf-package.html#cb29-3" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>), </span>
<span id="cb29-4"><a href="introduction-to-the-sf-package.html#cb29-4" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), </span>
<span id="cb29-5"><a href="introduction-to-the-sf-package.html#cb29-5" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">2</span>),</span>
<span id="cb29-6"><a href="introduction-to-the-sf-package.html#cb29-6" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">2</span>,<span class="dv">1</span>),</span>
<span id="cb29-7"><a href="introduction-to-the-sf-package.html#cb29-7" tabindex="-1"></a>                <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>)</span>
<span id="cb29-8"><a href="introduction-to-the-sf-package.html#cb29-8" tabindex="-1"></a>        )</span>
<span id="cb29-9"><a href="introduction-to-the-sf-package.html#cb29-9" tabindex="-1"></a></span>
<span id="cb29-10"><a href="introduction-to-the-sf-package.html#cb29-10" tabindex="-1"></a>polygon1 <span class="ot">&lt;-</span> <span class="fu">st_polygon</span>(<span class="fu">list</span>(polygon_coordinates))</span>
<span id="cb29-11"><a href="introduction-to-the-sf-package.html#cb29-11" tabindex="-1"></a></span>
<span id="cb29-12"><a href="introduction-to-the-sf-package.html#cb29-12" tabindex="-1"></a><span class="fu">plot</span>(polygon1)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-19-1.png" width="672" />
<br/></p>
<p><em>MultiLineStrings</em> and <em>Multipolygons</em> are also created with lists.</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="introduction-to-the-sf-package.html#cb30-1" tabindex="-1"></a>multilinestring_coordinates1 <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">3</span>), <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">4</span>))</span>
<span id="cb30-2"><a href="introduction-to-the-sf-package.html#cb30-2" tabindex="-1"></a>multilinestring_coordinates2 <span class="ot">&lt;-</span> <span class="fu">rbind</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">0</span>), <span class="fu">c</span>(<span class="dv">3</span>, <span class="dv">0</span>), <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">0</span>), <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">1</span>))</span>
<span id="cb30-3"><a href="introduction-to-the-sf-package.html#cb30-3" tabindex="-1"></a>multilinestring_coordinates <span class="ot">&lt;-</span> <span class="fu">list</span>(multilinestring_coordinates1, multilinestring_coordinates2)</span>
<span id="cb30-4"><a href="introduction-to-the-sf-package.html#cb30-4" tabindex="-1"></a>multilinestring1 <span class="ot">&lt;-</span> <span class="fu">st_multilinestring</span>(multilinestring_coordinates)</span>
<span id="cb30-5"><a href="introduction-to-the-sf-package.html#cb30-5" tabindex="-1"></a><span class="fu">plot</span>(multilinestring1)        </span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-20-1.png" width="672" />
<br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.7</strong></p>
</div>
<p>Extend the coordinates of the line you created in exercise 1.6 to become a polygon.</p>
</div>
<p><br/></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="introduction-to-the-sf-package.html#cb31-1" tabindex="-1"></a>multipolygon_coordinates <span class="ot">&lt;-</span></span>
<span id="cb31-2"><a href="introduction-to-the-sf-package.html#cb31-2" tabindex="-1"></a>        <span class="fu">list</span>(</span>
<span id="cb31-3"><a href="introduction-to-the-sf-package.html#cb31-3" tabindex="-1"></a>                <span class="fu">list</span>(</span>
<span id="cb31-4"><a href="introduction-to-the-sf-package.html#cb31-4" tabindex="-1"></a>                        <span class="fu">rbind</span>(<span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>), <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">1</span>), <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">0</span>), <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>))</span>
<span id="cb31-5"><a href="introduction-to-the-sf-package.html#cb31-5" tabindex="-1"></a>                        ), </span>
<span id="cb31-6"><a href="introduction-to-the-sf-package.html#cb31-6" tabindex="-1"></a>                <span class="fu">list</span>(</span>
<span id="cb31-7"><a href="introduction-to-the-sf-package.html#cb31-7" tabindex="-1"></a>                        <span class="fu">rbind</span>(<span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>), <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>), <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>), <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>), <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>))</span>
<span id="cb31-8"><a href="introduction-to-the-sf-package.html#cb31-8" tabindex="-1"></a>                        )</span>
<span id="cb31-9"><a href="introduction-to-the-sf-package.html#cb31-9" tabindex="-1"></a>                )</span>
<span id="cb31-10"><a href="introduction-to-the-sf-package.html#cb31-10" tabindex="-1"></a></span>
<span id="cb31-11"><a href="introduction-to-the-sf-package.html#cb31-11" tabindex="-1"></a>multipolygon1 <span class="ot">&lt;-</span> <span class="fu">st_multipolygon</span>(multipolygon_coordinates)</span>
<span id="cb31-12"><a href="introduction-to-the-sf-package.html#cb31-12" tabindex="-1"></a></span>
<span id="cb31-13"><a href="introduction-to-the-sf-package.html#cb31-13" tabindex="-1"></a><span class="fu">plot</span>(multipolygon1)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-21-1.png" width="672" />
<br/></p>
<p><em>Geometry collections</em> are single geometric objects, i.e., a single row in an sf object, that combine different <em>GeometryTypes.</em></p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="introduction-to-the-sf-package.html#cb32-1" tabindex="-1"></a>geometrycollection1 <span class="ot">&lt;-</span></span>
<span id="cb32-2"><a href="introduction-to-the-sf-package.html#cb32-2" tabindex="-1"></a>        <span class="fu">st_geometrycollection</span>(<span class="at">x =</span> <span class="fu">list</span>(</span>
<span id="cb32-3"><a href="introduction-to-the-sf-package.html#cb32-3" tabindex="-1"></a>                <span class="fu">st_multipolygon</span>(multipolygon_coordinates),</span>
<span id="cb32-4"><a href="introduction-to-the-sf-package.html#cb32-4" tabindex="-1"></a>                <span class="fu">st_multilinestring</span>(multilinestring_coordinates)</span>
<span id="cb32-5"><a href="introduction-to-the-sf-package.html#cb32-5" tabindex="-1"></a>        ))</span>
<span id="cb32-6"><a href="introduction-to-the-sf-package.html#cb32-6" tabindex="-1"></a><span class="fu">plot</span>(geometrycollection1)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-22-1.png" width="672" />
<br/></p>
</div>
<div id="basic-operations" class="section level2 hasAnchor" number="1.3">
<h2><span class="header-section-number">1.3</span> Basic operations<a href="introduction-to-the-sf-package.html#basic-operations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>So far, our objects have geometric shapes, but they are not truly <em>spatial</em>.
They are not connected to locations on earth, because they don’t have a coordinate reference system (CRS).
With the command <code>st_crs()</code>, we assign a CRS to an sf object.
Alternatively, we can do this in <code>st_sfc()</code> when we turn an <code>sfg</code> into an <code>sfc</code> or in <code>st_as_sf</code> when we turn an <code>sfc</code> into an <code>sf</code>.
We can use different formats to describe the CRS, but in practice the EPSG code is the easiest.
We assign <code>geometrycollection1</code> the CRS World Geodetic Survey 1984 (WGS84) with the EPSG code 4326.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="introduction-to-the-sf-package.html#cb33-1" tabindex="-1"></a>geometrycollection_sfc <span class="ot">&lt;-</span> <span class="fu">st_sfc</span>(geometrycollection1, <span class="at">crs =</span> <span class="st">&quot;EPSG:4326&quot;</span>)</span>
<span id="cb33-2"><a href="introduction-to-the-sf-package.html#cb33-2" tabindex="-1"></a>geometrycollection_sf  <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(geometrycollection_sfc)</span></code></pre></div>
<p><br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.8</strong></p>
</div>
<ul>
<li>Create a geometry collection<br />
</li>
<li>Create two version of this geometry collection. Once with the CRS EPSG:3035 and once with the CRS EPSG:4326.</li>
</ul>
</div>
<p><br/></p>
<p>There are many superior alternatives to the <code>plot()</code> function to create maps in R.
Here, we will use the <code>tmap</code> package <span class="citation">(<a href="#ref-Tennekes2018">Tennekes 2018</a>)</span>.
Each <code>tmap</code> has at least two elements:<br />
1. <code>tm_shape()</code> The spatial object you want to map.<br />
2. the geometric shape you want to use: <code>tm_dots()</code> for points, <code>tm_lines()</code> for lines and <code>tm_polygons()</code> for polygons.</p>
<p>These elements are combined with a <code>+</code>.
There are no limits to how many objects or geometric shapes you can include in a single map.
If you want to use different objects in one map you can call <code>tm_shape()</code> again with the next object after the <code>+</code>.</p>
<pre><code>## Breaking News: tmap 3.x is retiring. Please test v4, e.g. with
## remotes::install_github(&#39;r-tmap/tmap&#39;)</code></pre>
<pre><code>## tmap mode set to plotting</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="introduction-to-the-sf-package.html#cb36-1" tabindex="-1"></a><span class="fu">library</span>(tmap)</span>
<span id="cb36-2"><a href="introduction-to-the-sf-package.html#cb36-2" tabindex="-1"></a><span class="fu">tm_shape</span>(geometrycollection_sf) <span class="sc">+</span> </span>
<span id="cb36-3"><a href="introduction-to-the-sf-package.html#cb36-3" tabindex="-1"></a>        <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb36-4"><a href="introduction-to-the-sf-package.html#cb36-4" tabindex="-1"></a>        <span class="fu">tm_lines</span>() <span class="sc">+</span> </span>
<span id="cb36-5"><a href="introduction-to-the-sf-package.html#cb36-5" tabindex="-1"></a>        <span class="fu">tm_polygons</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-25-1.png" width="672" />
<br/></p>
<p>With <code>tmap</code> you can create interactive and static maps.
Interactive maps are great to explore your data, to check if you have specified the correct CRS, or for interactive documents in html format like this book.
To create interactive maps you have to change the <code>tm_mode</code> from <code>"plot"</code> to <code>"view"</code>.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="introduction-to-the-sf-package.html#cb37-1" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">&quot;view&quot;</span>)</span></code></pre></div>
<pre><code>## tmap mode set to interactive viewing</code></pre>
<p>After that, the same function as before will create interactive maps.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="introduction-to-the-sf-package.html#cb39-1" tabindex="-1"></a><span class="fu">tm_shape</span>(geometrycollection_sf) <span class="sc">+</span> </span>
<span id="cb39-2"><a href="introduction-to-the-sf-package.html#cb39-2" tabindex="-1"></a>        <span class="fu">tm_dots</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span> </span>
<span id="cb39-3"><a href="introduction-to-the-sf-package.html#cb39-3" tabindex="-1"></a>        <span class="fu">tm_lines</span>() <span class="sc">+</span> </span>
<span id="cb39-4"><a href="introduction-to-the-sf-package.html#cb39-4" tabindex="-1"></a>        <span class="fu">tm_polygons</span>()</span></code></pre></div>
<div class="leaflet html-widget html-fill-item" id="htmlwidget-32741c8768f14cdf5db5" style="width:672px;height:480px;"></div>
<script type="application/json" data-for="htmlwidget-32741c8768f14cdf5db5">{"x":{"options":{"crs":{"crsClass":"L.CRS.EPSG3857","code":null,"proj4def":null,"projectedBounds":null,"options":{}}},"calls":[{"method":"createMapPane","args":["tmap401",401]},{"method":"createMapPane","args":["tmap402",402]},{"method":"createMapPane","args":["tmap403",403]},{"method":"createMapPane","args":["tmap404",404]},{"method":"addProviderTiles","args":["Esri.WorldGrayCanvas",null,"Esri.WorldGrayCanvas",{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"pane":"tilePane"}]},{"method":"addProviderTiles","args":["OpenStreetMap",null,"OpenStreetMap",{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"pane":"tilePane"}]},{"method":"addProviderTiles","args":["Esri.WorldTopoMap",null,"Esri.WorldTopoMap",{"minZoom":0,"maxZoom":18,"tileSize":256,"subdomains":"abc","errorTileUrl":"","tms":false,"noWrap":false,"zoomOffset":0,"zoomReverse":false,"opacity":1,"zIndex":1,"detectRetina":false,"pane":"tilePane"}]},{"method":"addCircleMarkers","args":[[0.5,1.5],[0.5,1.5],[20,20],[null,null],"geometrycollection_sf",{"interactive":true,"className":"","pane":"tmap401","stroke":true,"color":"#666666","weight":1,"opacity":0.5,"fill":true,"fillColor":["#000000","#000000"],"fillOpacity":[1,1]},null,null,null,null,[null,null],{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addPolygons","args":[[[[{"lng":[0,0,1,1,0],"lat":[0,1,1,0,0]}]],[[{"lng":[2,2,1,1,2],"lat":[1,2,2,1,1]}]]],["X1","X1.1"],"geometrycollection_sf",{"interactive":true,"className":"","pane":"tmap402","stroke":true,"color":"#666666","weight":1,"opacity":1,"fill":true,"fillColor":["#D9D9D9","#D9D9D9"],"fillOpacity":[1,1],"dashArray":"none","smoothFactor":1,"noClip":false},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addCircleMarkers","args":[[2.5,0],[1,3.5],[20,20],[null,"X1.1"],"geometrycollection_sf",{"interactive":true,"className":"","pane":"tmap403","stroke":true,"color":"#666666","weight":1,"opacity":0.5,"fill":true,"fillColor":["#000000","#000000"],"fillOpacity":[1,1]},null,null,null,null,[null,null],{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addPolylines","args":[[[[{"lng":[1,1,1,1],"lat":[1,2,3,4]}]],[[{"lng":[2,3,4,4],"lat":[0,0,0,1]}]]],["X1.2","X1.3"],"geometrycollection_sf",{"interactive":true,"className":"","pane":"tmap404","stroke":true,"color":["#000000","#000000"],"weight":[1,1],"opacity":[1,1],"fill":false,"fillColor":["#000000","#000000"],"fillOpacity":0.2,"dashArray":"none","smoothFactor":1,"noClip":false},null,null,null,{"interactive":false,"permanent":false,"direction":"auto","opacity":1,"offset":[0,0],"textsize":"10px","textOnly":false,"className":"","sticky":true},null]},{"method":"addLayersControl","args":[["Esri.WorldGrayCanvas","OpenStreetMap","Esri.WorldTopoMap"],"geometrycollection_sf",{"collapsed":true,"autoZIndex":true,"position":"topleft"}]}],"limits":{"lat":[0,4],"lng":[0,4]},"fitBounds":[0,0,4,4,[]]},"evals":[],"jsHooks":[]}</script>
<p><br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.9</strong></p>
</div>
<ul>
<li>Create an interactive map in which you display the geometry collection from Exercise 1.8.<br />
</li>
<li>Why are the objects apart? Whats the main difference between the two CRS? Discuss with your neighbor.<br />
</li>
</ul>
</div>
<p><br/></p>
</div>
<div id="useful-functions" class="section level2 hasAnchor" number="1.4">
<h2><span class="header-section-number">1.4</span> Useful functions<a href="introduction-to-the-sf-package.html#useful-functions" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>The names of the functions in <code>sf</code> are mostly self-explanatory.
You can often just type <code>sf::</code>, scroll through the list of functions that appears, and with some background knowledge and imagination you’ll find what you’re looking for. This works especially well if you combine this tactic with the help function (?function_name or highlight function in editor and press F1). So, let’s have a look at some useful functions.</p>
<div id="st_area" class="section level3 hasAnchor" number="1.4.1">
<h3><span class="header-section-number">1.4.1</span> <code>st_area</code><a href="introduction-to-the-sf-package.html#st_area" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With <code>st_area()</code> we can determine the area of polygons.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="introduction-to-the-sf-package.html#cb40-1" tabindex="-1"></a>germany_area <span class="ot">&lt;-</span> <span class="fu">st_area</span>(germany)</span>
<span id="cb40-2"><a href="introduction-to-the-sf-package.html#cb40-2" tabindex="-1"></a>germany_area[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>## Units: [m^2]
##  [1]  53640075 105002330  54804352  54609171  86775447 202944902  62872917  50128777 171435663 220499041</code></pre>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="introduction-to-the-sf-package.html#cb42-1" tabindex="-1"></a><span class="fu">class</span>(germany_area)</span></code></pre></div>
<pre><code>## [1] &quot;units&quot;</code></pre>
<p><code>germany_area</code> has the class <code>units</code> which was introduced by the eponymous <a href="https://r-quantities.github.io/units/articles/measurement_units_in_R.html">package</a> <span class="citation">(<a href="#ref-Pebesma2016">Pebesma, Mailund, and Hiebert 2016</a>)</span>.
This package is really handy. It allows for automatic propagation, conversion, derivation and simplification of units. It also raises errors in case of unit incompatibility. For example, we can transform the areas we just computed from square meters to square kilometers</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="introduction-to-the-sf-package.html#cb44-1" tabindex="-1"></a>km2_areas <span class="ot">&lt;-</span> units<span class="sc">::</span><span class="fu">set_units</span>(germany_area, <span class="st">&quot;km2&quot;</span>)</span>
<span id="cb44-2"><a href="introduction-to-the-sf-package.html#cb44-2" tabindex="-1"></a>km2_areas[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>## Units: [km^2]
##  [1]  53.64008 105.00233  54.80435  54.60917  86.77545 202.94490  62.87292  50.12878 171.43566 220.49904</code></pre>
<p>If I now try to combine the measurements in <span class="math inline">\(m^2\)</span> and <span class="math inline">\(km^2\)</span>, this still works</p>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="introduction-to-the-sf-package.html#cb46-1" tabindex="-1"></a>subst <span class="ot">&lt;-</span> km2_areas <span class="sc">-</span> germany_area</span>
<span id="cb46-2"><a href="introduction-to-the-sf-package.html#cb46-2" tabindex="-1"></a>subst[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span></code></pre></div>
<pre><code>## Units: [km^2]
##  [1] 0 0 0 0 0 0 0 0 0 0</code></pre>
<p>Even if <code>units</code> is quite handy, some functions can’t handle this object class properly.
It often makes sense to transform the objects back to ordinary numbers.
With <code>units::drop_units()</code>, we can convert the object into simple numbers.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="introduction-to-the-sf-package.html#cb48-1" tabindex="-1"></a>germany_area <span class="ot">&lt;-</span> units<span class="sc">::</span><span class="fu">drop_units</span>(germany_area)</span></code></pre></div>
<p>To visualize what we have just computed, it would be great to make map, in which every polygon is colored according to its area. To do this, we first create a variable called <code>area</code> in <code>germany</code> with the <code>mutate()</code> function from the <code>dplyr</code> <a href="https://dplyr.tidyverse.org/">package</a> <span class="citation">(<a href="#ref-Wickham2022">Wickham et al. 2022</a>)</span>.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb49-1"><a href="introduction-to-the-sf-package.html#cb49-1" tabindex="-1"></a>germany <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">mutate</span>(germany, <span class="at">area =</span> germany_area)  </span></code></pre></div>
<p><br/></p>
<div class="sourceCode" id="cb50"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb50-1"><a href="introduction-to-the-sf-package.html#cb50-1" tabindex="-1"></a><span class="fu">tmap_mode</span>(<span class="st">&quot;plot&quot;</span>)</span></code></pre></div>
<pre><code>## tmap mode set to plotting</code></pre>
<div class="sourceCode" id="cb52"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb52-1"><a href="introduction-to-the-sf-package.html#cb52-1" tabindex="-1"></a><span class="fu">tm_shape</span>(germany) <span class="sc">+</span> <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;area&quot;</span>) <span class="sc">+</span> <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-33-1.png" width="672" /></p>
<p>The mapview Package only has one important function, <code>mapview()</code>. With the <code>zcol</code> argument, we set the name of the column that determines the color. However, this is not obligatory.</p>
<p><br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.10</strong></p>
</div>
<ul>
<li>Compute the size of German administrative districts.<br />
</li>
<li>Transform the size to square kilometers.</li>
<li>Add the area as a variable to the administrative districts object.</li>
<li>Select and plot only those districts that are larger than the median district size.</li>
</ul>
</div>
<p><br/></p>
</div>
<div id="st_bbox" class="section level3 hasAnchor" number="1.4.2">
<h3><span class="header-section-number">1.4.2</span> <code>st_bbox()</code><a href="introduction-to-the-sf-package.html#st_bbox" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With the <code>st_bbox()</code> function we can extract the bounding box from an sf object.</p>
<div class="sourceCode" id="cb53"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb53-1"><a href="introduction-to-the-sf-package.html#cb53-1" tabindex="-1"></a>bb <span class="ot">&lt;-</span> <span class="fu">st_bbox</span>(germany)</span>
<span id="cb53-2"><a href="introduction-to-the-sf-package.html#cb53-2" tabindex="-1"></a>bb</span></code></pre></div>
<pre><code>##      xmin      ymin      xmax      ymax 
##  5.866251 47.270123 15.041815 55.056526</code></pre>
<p>As you can see, this is not an sf object but …</p>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="introduction-to-the-sf-package.html#cb55-1" tabindex="-1"></a><span class="fu">class</span>(bb)</span></code></pre></div>
<pre><code>## [1] &quot;bbox&quot;</code></pre>
<p>… a bbox. Technically, this is just a named vector with four elements. However, sf can easily turn this into a polygon.</p>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="introduction-to-the-sf-package.html#cb57-1" tabindex="-1"></a>bb2 <span class="ot">&lt;-</span> <span class="fu">st_as_sfc</span>(bb)</span>
<span id="cb57-2"><a href="introduction-to-the-sf-package.html#cb57-2" tabindex="-1"></a>bb2 <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(bb2)</span>
<span id="cb57-3"><a href="introduction-to-the-sf-package.html#cb57-3" tabindex="-1"></a><span class="fu">tm_shape</span>(bb2) <span class="sc">+</span> <span class="fu">tm_borders</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-36-1.png" width="672" /></p>
</div>
<div id="st_buffer" class="section level3 hasAnchor" number="1.4.3">
<h3><span class="header-section-number">1.4.3</span> <code>st_buffer()</code><a href="introduction-to-the-sf-package.html#st_buffer" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>If we want to buffer data, this is done with <code>st_buffer()</code>.
To demonstrate this function, we will use <code>dplyr::filter()</code>, and select only one district in the Germany data.</p>
<div class="sourceCode" id="cb58"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb58-1"><a href="introduction-to-the-sf-package.html#cb58-1" tabindex="-1"></a>goslar <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(germany, NAME_2 <span class="sc">==</span> <span class="st">&quot;Goslar&quot;</span>)</span>
<span id="cb58-2"><a href="introduction-to-the-sf-package.html#cb58-2" tabindex="-1"></a><span class="fu">tm_shape</span>(goslar) <span class="sc">+</span> <span class="fu">tm_polygons</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-37-1.png" width="672" /></p>
<div class="sourceCode" id="cb59"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb59-1"><a href="introduction-to-the-sf-package.html#cb59-1" tabindex="-1"></a>goslar2 <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(goslar, <span class="dv">100</span>)</span>
<span id="cb59-2"><a href="introduction-to-the-sf-package.html#cb59-2" tabindex="-1"></a><span class="fu">tm_shape</span>(goslar2) <span class="sc">+</span> <span class="fu">tm_polygons</span>(<span class="at">alpha =</span> .<span class="dv">6</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-37-2.png" width="672" /></p>
<p><br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.11</strong></p>
</div>
<ul>
<li>select another district from Germany<br />
</li>
<li>buffer your district by 1000 meters</li>
</ul>
</div>
<p><br/></p>
</div>
<div id="st_coordinates" class="section level3 hasAnchor" number="1.4.4">
<h3><span class="header-section-number">1.4.4</span> <code>st_coordinates()</code><a href="introduction-to-the-sf-package.html#st_coordinates" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>sf</code> can work with not inherently spatial file formats, like .csv.
For this, we first load the .csv file picea_abies.csv <a href="https://seafile.rlp.net/f/86cd0c013a7f4deca4a4/?dl=1">here</a> into R using the base R function <code>read.csv()</code>.</p>
<div class="sourceCode" id="cb60"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb60-1"><a href="introduction-to-the-sf-package.html#cb60-1" tabindex="-1"></a>csv_data <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;data/picea_abies.csv&quot;</span>)</span></code></pre></div>
<p>Let’s have a look at the data.</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="introduction-to-the-sf-package.html#cb61-1" tabindex="-1"></a><span class="fu">head</span>(csv_data)</span></code></pre></div>
<pre><code>##                                                              locality         X        Y
## 1                                                             Abtwald 12.918306 50.70953
## 2                                Pastorenbruch, Kupferberg, Bärenhöhe 10.789557 51.65258
## 3                            FFH-Gebiet 5322-306 Lauter und Eisenbach  9.344114 50.60485
## 4 NSG Feldatal (FFH-Teilgebiet 5320-303 Feldatal/Kahlofen und Ohmaue)  9.139766 50.68140
## 5                                          NSG Battenfelder Driescher  8.638373 51.04513
## 6                                                        Eckerstausee 10.589198 51.83755</code></pre>
<p>We have a location name and two coordinates. We can turn this into an sf object with the <code>st_as_sf()</code> function.
All we need is the object, the names of the columns that contain the X and Y coordinates, and the coordinates reference system. For the latter, the EPSG code is typically sufficient.</p>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="introduction-to-the-sf-package.html#cb63-1" tabindex="-1"></a>csv_data.sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(</span>
<span id="cb63-2"><a href="introduction-to-the-sf-package.html#cb63-2" tabindex="-1"></a>        <span class="at">x =</span> csv_data, </span>
<span id="cb63-3"><a href="introduction-to-the-sf-package.html#cb63-3" tabindex="-1"></a>        <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">&quot;X&quot;</span>, <span class="st">&quot;Y&quot;</span>),</span>
<span id="cb63-4"><a href="introduction-to-the-sf-package.html#cb63-4" tabindex="-1"></a>        <span class="at">crs =</span> <span class="dv">4326</span></span>
<span id="cb63-5"><a href="introduction-to-the-sf-package.html#cb63-5" tabindex="-1"></a>)</span></code></pre></div>
<div class="sourceCode" id="cb64"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb64-1"><a href="introduction-to-the-sf-package.html#cb64-1" tabindex="-1"></a>csv_data.sf</span></code></pre></div>
<pre><code>## Simple feature collection with 7942 features and 1 field
## Geometry type: POINT
## Dimension:     XY
## Bounding box:  xmin: 8.110204 ymin: 50.28763 xmax: 13.30139 ymax: 52.60144
## Geodetic CRS:  WGS 84
## First 10 features:
##                                                               locality                  geometry
## 1                                                              Abtwald POINT (12.91831 50.70953)
## 2                                 Pastorenbruch, Kupferberg, Bärenhöhe POINT (10.78956 51.65258)
## 3                             FFH-Gebiet 5322-306 Lauter und Eisenbach POINT (9.344114 50.60485)
## 4  NSG Feldatal (FFH-Teilgebiet 5320-303 Feldatal/Kahlofen und Ohmaue)  POINT (9.139766 50.6814)
## 5                                           NSG Battenfelder Driescher POINT (8.638373 51.04513)
## 6                                                         Eckerstausee  POINT (10.5892 51.83755)
## 7                               Stadtwald Mengeringhausen und Umgebung  POINT (8.947862 51.3599)
## 8                                     Taunus bei Hausen, Am Hühnerturm POINT (8.630587 50.42718)
## 9                                                    Löhlbach, Wesetal POINT (8.974815 51.07919)
## 10                                              Bohngartental Marksuhl POINT (10.21233 50.91634)</code></pre>
<p>Note that the columns containing the coordinates (X and Y) were replaced by the geometry column.</p>
<div class="sourceCode" id="cb66"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb66-1"><a href="introduction-to-the-sf-package.html#cb66-1" tabindex="-1"></a><span class="fu">tm_shape</span>(csv_data.sf) <span class="sc">+</span> <span class="fu">tm_dots</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-42-1.png" width="672" /></p>
<p>Here, I deactivated the legend (<code>legend = FALSE</code>) because there is too many elements.</p>
<p>When we transform the sf object back to a data.frame we still keep the geometry column.</p>
<div class="sourceCode" id="cb67"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb67-1"><a href="introduction-to-the-sf-package.html#cb67-1" tabindex="-1"></a>csv_data2 <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(csv_data.sf)</span></code></pre></div>
<p>To get the coordinates back we can use the <code>st_coordinates()</code> function. The function creats a matrix with coordinates.</p>
<div class="sourceCode" id="cb68"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb68-1"><a href="introduction-to-the-sf-package.html#cb68-1" tabindex="-1"></a>coord <span class="ot">&lt;-</span> <span class="fu">st_coordinates</span>(csv_data.sf)</span>
<span id="cb68-2"><a href="introduction-to-the-sf-package.html#cb68-2" tabindex="-1"></a><span class="fu">head</span>(coord)</span></code></pre></div>
<pre><code>##              X        Y
## [1,] 12.918306 50.70953
## [2,] 10.789557 51.65258
## [3,]  9.344114 50.60485
## [4,]  9.139766 50.68140
## [5,]  8.638373 51.04513
## [6,] 10.589198 51.83755</code></pre>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.12</strong></p>
</div>
<ul>
<li>load the picea abies data<br />
</li>
<li>turn the data set into an sf object<br />
</li>
<li>extract the coordinates from the sf object<br />
</li>
</ul>
</div>
<p><br/></p>
</div>
</div>
<div id="geometric-set-operations" class="section level2 hasAnchor" number="1.5">
<h2><span class="header-section-number">1.5</span> Geometric set operations<a href="introduction-to-the-sf-package.html#geometric-set-operations" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>There are four distinct geometric operations for pairs of simple feature geometries:<br />
1. st_intersection</p>
<ol start="4" style="list-style-type: decimal">
<li>st_snap</li>
</ol>
<div class="sourceCode" id="cb70"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb70-1"><a href="introduction-to-the-sf-package.html#cb70-1" tabindex="-1"></a>knitr<span class="sc">::</span><span class="fu">include_graphics</span>(<span class="st">&quot;images/binary_operation.png&quot;</span>)</span></code></pre></div>
<p><img src="images/binary_operation.png" width="500" /></p>
<p>Basically, all of these functions take two arguments (<code>x</code> and <code>y</code>) — two simple feature geometries (i.e., sf objects), which are combined in some way. We will use the <a href="https://www.bmuv.de/themen/naturschutz/gebietsschutz-und-vernetzung/natura-2000/schutzgebietsnetz-natura-2000">natura2000</a> area in Germany as a demonstration. You can download the data <a href="https://seafile.rlp.net/d/a3fe7fd7835e43cbaccc/">here</a>. <code>st_intersection()</code> checks whether <code>x</code> and <code>y</code> intersect.</p>
<div class="sourceCode" id="cb71"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb71-1"><a href="introduction-to-the-sf-package.html#cb71-1" tabindex="-1"></a>natura2000 <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">&quot;data/natura 2000/natura2000_deutschland.gpkg&quot;</span>)</span></code></pre></div>
<pre><code>## Reading layer `intersection&#39; from data source `C:\Users\jonat\Documents\001_Uni\002_teaching\online books\book_spatial_data_science_in_R\data\natura 2000\natura2000_deutschland.gpkg&#39; using driver `GPKG&#39;
## Simple feature collection with 5274 features and 100 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 4038514 ymin: 2684315 xmax: 4671424 ymax: 3552221
## Projected CRS: ETRS89-extended / LAEA Europe</code></pre>
<p>This data set has many variables we don’t care about. We will clean it up first.</p>
<div class="sourceCode" id="cb73"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb73-1"><a href="introduction-to-the-sf-package.html#cb73-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span></code></pre></div>
<pre><code>## 
## Attache Paket: &#39;dplyr&#39;</code></pre>
<pre><code>## Die folgenden Objekte sind maskiert von &#39;package:stats&#39;:
## 
##     filter, lag</code></pre>
<pre><code>## Die folgenden Objekte sind maskiert von &#39;package:base&#39;:
## 
##     intersect, setdiff, setequal, union</code></pre>
<div class="sourceCode" id="cb77"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb77-1"><a href="introduction-to-the-sf-package.html#cb77-1" tabindex="-1"></a>natura2000 <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">select</span>(natura2000, </span>
<span id="cb77-2"><a href="introduction-to-the-sf-package.html#cb77-2" tabindex="-1"></a>                     SITENAME, </span>
<span id="cb77-3"><a href="introduction-to-the-sf-package.html#cb77-3" tabindex="-1"></a>                     SOVEREIGNT)</span></code></pre></div>
<p>Let’s have a look at the data.</p>
<div class="sourceCode" id="cb78"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb78-1"><a href="introduction-to-the-sf-package.html#cb78-1" tabindex="-1"></a><span class="fu">tm_shape</span>(natura2000) <span class="sc">+</span> <span class="fu">tm_borders</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-48-1.png" width="672" /></p>
<p>To render this data set simpler, we will reduce it to areas within a 100km radius around Goslar.</p>
<p>First, we create a buffer. For this we need to unify Goslar. Currently Goslar consist of multiple Polygons — one for each administrative unit. If we buffer goslar, each polygon is buffered independently. We can quickly play through this.</p>
<div class="sourceCode" id="cb79"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb79-1"><a href="introduction-to-the-sf-package.html#cb79-1" tabindex="-1"></a>many_buffer <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(goslar, <span class="dv">1000</span>)</span>
<span id="cb79-2"><a href="introduction-to-the-sf-package.html#cb79-2" tabindex="-1"></a><span class="fu">tm_shape</span>(many_buffer) <span class="sc">+</span> <span class="fu">tm_polygons</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-49-1.png" width="672" /></p>
<p>The dark blue areas are overlapping areas.</p>
<p>What we want instead is a singe polygon including all of <code>goslar</code>. We want to dissolve the internal boundaries.
We can do this with <code>st_union()</code>. The result of <code>st_union()</code> is an <code>sfc</code> object, so we need to turn it back into an <code>sf</code> object with <code>st_as_sf()</code>.</p>
<div class="sourceCode" id="cb80"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb80-1"><a href="introduction-to-the-sf-package.html#cb80-1" tabindex="-1"></a>goslar2 <span class="ot">&lt;-</span> <span class="fu">st_union</span>(goslar) <span class="sc">%&gt;%</span> <span class="fu">st_as_sf</span>()</span>
<span id="cb80-2"><a href="introduction-to-the-sf-package.html#cb80-2" tabindex="-1"></a><span class="fu">tm_shape</span>(goslar2) <span class="sc">+</span> <span class="fu">tm_polygons</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-50-1.png" width="672" /></p>
<div class="sourceCode" id="cb81"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb81-1"><a href="introduction-to-the-sf-package.html#cb81-1" tabindex="-1"></a>goslar100k <span class="ot">&lt;-</span> <span class="fu">st_buffer</span>(goslar2, <span class="at">dist =</span> <span class="dv">100000</span>)</span></code></pre></div>
<p>Then we harmonize the CRSs.</p>
<div class="sourceCode" id="cb82"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb82-1"><a href="introduction-to-the-sf-package.html#cb82-1" tabindex="-1"></a>goslar100k <span class="ot">&lt;-</span> <span class="fu">st_transform</span>(goslar100k, <span class="at">crs =</span> <span class="fu">st_crs</span>(natura2000))</span></code></pre></div>
<p>Now lets proceed to the intersection.</p>
<div class="sourceCode" id="cb83"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb83-1"><a href="introduction-to-the-sf-package.html#cb83-1" tabindex="-1"></a>natura2000xgoslar <span class="ot">&lt;-</span> <span class="fu">st_intersection</span>(natura2000, goslar100k)</span></code></pre></div>
<pre><code>## Warning: attribute variables are assumed to be spatially constant throughout all geometries</code></pre>
<div class="sourceCode" id="cb85"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb85-1"><a href="introduction-to-the-sf-package.html#cb85-1" tabindex="-1"></a><span class="fu">tm_shape</span>(natura2000xgoslar) <span class="sc">+</span> <span class="fu">tm_polygons</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-52-1.png" width="672" /></p>
<p>The result only shows the parts of <code>natura2000</code> that fall within the 1000 kilometer buffer around <code>goslar</code> The resulting object has all variables from <code>goslar2</code> and <code>natura2000</code> but because <code>goslar2</code> did not have any variables, it’s actually just those from <code>natura2000</code>.</p>
<div class="sourceCode" id="cb86"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb86-1"><a href="introduction-to-the-sf-package.html#cb86-1" tabindex="-1"></a><span class="fu">head</span>(natura2000xgoslar)</span></code></pre></div>
<pre><code>## Simple feature collection with 6 features and 2 fields
## Geometry type: POLYGON
## Dimension:     XY
## Bounding box:  xmin: 4244053 ymin: 3073390 xmax: 4395728 ymax: 3252810
## Projected CRS: ETRS89-extended / LAEA Europe
##                                      SITENAME SOVEREIGNT                           geom
## 4              Binnensalzstelle Klein Oedesse    Germany POLYGON ((4336116 3252773, ...
## 6                                    Huxstein    Germany POLYGON ((4244128 3153234, ...
## 8                              NSG Tännreisig    Germany POLYGON ((4395689 3073831, ...
## 434 Bachlauf der Warme von Ehlen bis Liebenau    Germany POLYGON ((4273429 3150123, ...
## 435                              Ballertasche    Germany POLYGON ((4296055 3149374, ...
## 457                            Wendesser Moor    Germany POLYGON ((4337001 3250162, ...</code></pre>
<p>Note that the <code>natura2000</code> polygons at the border of the buffer where cut off there.
There is a second option to perform intersections with <code>sf</code>, with the <code>st_intersects()</code> function.</p>
<div class="sourceCode" id="cb88"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb88-1"><a href="introduction-to-the-sf-package.html#cb88-1" tabindex="-1"></a>inter2 <span class="ot">&lt;-</span> <span class="fu">st_intersects</span>(natura2000, goslar100k)</span>
<span id="cb88-2"><a href="introduction-to-the-sf-package.html#cb88-2" tabindex="-1"></a>inter2</span></code></pre></div>
<pre><code>## Sparse geometry binary predicate list of length 5274, where the predicate was `intersects&#39;
## first 10 elements:
##  1: (empty)
##  2: (empty)
##  3: (empty)
##  4: 1
##  5: (empty)
##  6: 1
##  7: (empty)
##  8: 1
##  9: (empty)
##  10: (empty)</code></pre>
<p><code>inter2</code> is a sparse geometry binary predicate (sgbp). It is a list with as many elements as <code>natura2000</code> (5274). Each row thus corresponds to one row in <code>natura2000.</code> The number in that row indicates with which element of <code>goslar100k</code> the row intersects.</p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.13</strong></p>
</div>
<ul>
<li>Is there any other element than 1 in inter2?<br />
</li>
</ul>
</div>
<p><br/></p>
<p>With <code>apply(X, margin, FUN)</code> we can apply a function (<code>FUN</code>) to the elements of <code>X</code>. The margin determines it it is applied to each row (<code>margin = 1</code>) or to each column (<code>margin = 2</code>). So <code>apply(data_example,2,sum)</code> would compute the column sums of data_example. With …</p>
<div class="sourceCode" id="cb90"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb90-1"><a href="introduction-to-the-sf-package.html#cb90-1" tabindex="-1"></a>intersection_index <span class="ot">&lt;-</span> <span class="fu">apply</span>(inter2,<span class="dv">1</span>,any)</span></code></pre></div>
<p>… we get a vector of TRUE and FALSE. It is TRUE if the corresponding line in <code>inter2</code> holds a value and FALSE if that line is empty. With this vector we can subset <code>natura2000</code> to the intersecting elements.</p>
<div class="sourceCode" id="cb91"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb91-1"><a href="introduction-to-the-sf-package.html#cb91-1" tabindex="-1"></a>natura2000xgoslar2 <span class="ot">&lt;-</span> natura2000[intersection_index,]</span></code></pre></div>
<p>This basically works the same with <code>st_difference()</code> for the difference.</p>
<div class="sourceCode" id="cb92"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb92-1"><a href="introduction-to-the-sf-package.html#cb92-1" tabindex="-1"></a>natura2000noGoslar <span class="ot">&lt;-</span> <span class="fu">st_difference</span>(natura2000, goslar100k)</span></code></pre></div>
<pre><code>## Warning: attribute variables are assumed to be spatially constant throughout all geometries</code></pre>
<div class="sourceCode" id="cb94"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb94-1"><a href="introduction-to-the-sf-package.html#cb94-1" tabindex="-1"></a><span class="fu">tm_shape</span>(natura2000noGoslar) <span class="sc">+</span> <span class="fu">tm_polygons</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-57-1.png" width="672" /></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.14</strong></p>
</div>
<ul>
<li>Take any Kreis in Germany, unify it, and buffer it by 50 km<br />
</li>
<li>Intersect it with natura2000.<br />
</li>
<li>Now take the unbuffered Kreis to remove those areas from the intersection you created in the step before.<br />
</li>
</ul>
</div>
<div id="st_distance" class="section level3 hasAnchor" number="1.5.1">
<h3><span class="header-section-number">1.5.1</span> <code>st_distance</code><a href="introduction-to-the-sf-package.html#st_distance" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With <code>st_distance()</code> we can determine the distance between two objects.
The objects you want to use need to have an CRS otherwise R wont now what the distance unit is.
As a first example, we just pick to random German districts and compute the distance between them.</p>
<div class="sourceCode" id="cb95"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb95-1"><a href="introduction-to-the-sf-package.html#cb95-1" tabindex="-1"></a>district1 <span class="ot">&lt;-</span> germany[<span class="dv">10</span>,]</span>
<span id="cb95-2"><a href="introduction-to-the-sf-package.html#cb95-2" tabindex="-1"></a>district2 <span class="ot">&lt;-</span> germany[<span class="dv">100</span>,]</span></code></pre></div>
<div class="sourceCode" id="cb96"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb96-1"><a href="introduction-to-the-sf-package.html#cb96-1" tabindex="-1"></a><span class="fu">st_distance</span>(<span class="at">x =</span> district1, </span>
<span id="cb96-2"><a href="introduction-to-the-sf-package.html#cb96-2" tabindex="-1"></a>            <span class="at">y =</span> district2)</span></code></pre></div>
<pre><code>## Units: [m]
##          [,1]
## [1,] 85111.62</code></pre>
<p>We get a units matrix with the shortest distance between the two polygons.
Note, that this is not the distance between the centroids but between the borders of the polygons.
If we supply the function with vectors, the following happens:</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="introduction-to-the-sf-package.html#cb98-1" tabindex="-1"></a>district1 <span class="ot">&lt;-</span> germany[<span class="dv">8</span><span class="sc">:</span><span class="dv">10</span>,]</span>
<span id="cb98-2"><a href="introduction-to-the-sf-package.html#cb98-2" tabindex="-1"></a>district2 <span class="ot">&lt;-</span> germany[<span class="dv">98</span><span class="sc">:</span><span class="dv">100</span>,]</span>
<span id="cb98-3"><a href="introduction-to-the-sf-package.html#cb98-3" tabindex="-1"></a><span class="fu">st_distance</span>(<span class="at">x =</span> district1, </span>
<span id="cb98-4"><a href="introduction-to-the-sf-package.html#cb98-4" tabindex="-1"></a>            <span class="at">y =</span> district2)</span></code></pre></div>
<pre><code>## Units: [m]
##           [,1]      [,2]     [,3]
## [1,] 118532.39 116637.04 97183.43
## [2,]  82949.84  81943.49 61832.11
## [3,] 105208.29 105789.91 85111.62</code></pre>
<p>Now the distance matrix has three times three elements. Each gives the distance between two of the elements from the original vectors.
A question we might ask with this tool is are the ten largest districts closer to each other than the ten smallest.</p>
<div class="sourceCode" id="cb100"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb100-1"><a href="introduction-to-the-sf-package.html#cb100-1" tabindex="-1"></a>big10 <span class="ot">&lt;-</span> germany <span class="sc">|&gt;</span> </span>
<span id="cb100-2"><a href="introduction-to-the-sf-package.html#cb100-2" tabindex="-1"></a>        <span class="co"># sort by area, decreasing so smallest value on top </span></span>
<span id="cb100-3"><a href="introduction-to-the-sf-package.html#cb100-3" tabindex="-1"></a>        dplyr<span class="sc">::</span><span class="fu">arrange</span>(area) <span class="sc">|&gt;</span> </span>
<span id="cb100-4"><a href="introduction-to-the-sf-package.html#cb100-4" tabindex="-1"></a>        <span class="co"># take only the last 10 rows, i.e. the ten largest districts. </span></span>
<span id="cb100-5"><a href="introduction-to-the-sf-package.html#cb100-5" tabindex="-1"></a>        dplyr<span class="sc">::</span><span class="fu">slice_tail</span>(<span class="at">n =</span> <span class="dv">10</span>)</span>
<span id="cb100-6"><a href="introduction-to-the-sf-package.html#cb100-6" tabindex="-1"></a>big10 <span class="ot">&lt;-</span> <span class="fu">st_distance</span>(big10)</span></code></pre></div>
<p>This time, we only use one dataset, so the distance from each polygon to each polygon is calculated. In cell 3, row 2 is the distance from centroid of the third polygon to the second. Since the distance from the third to the second is equal to the distance from the second to the third, the matrix is symmetric. The diagonal contains the distances of objects to themselves, i.e. 0.</p>
<div class="sourceCode" id="cb101"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb101-1"><a href="introduction-to-the-sf-package.html#cb101-1" tabindex="-1"></a>big10 <span class="ot">&lt;-</span> big10 <span class="sc">|&gt;</span> units<span class="sc">::</span><span class="fu">drop_units</span>() </span>
<span id="cb101-2"><a href="introduction-to-the-sf-package.html#cb101-2" tabindex="-1"></a>big10 <span class="ot">&lt;-</span> big10[<span class="fu">upper.tri</span>(big10)]</span>
<span id="cb101-3"><a href="introduction-to-the-sf-package.html#cb101-3" tabindex="-1"></a>small10 <span class="ot">&lt;-</span> </span>
<span id="cb101-4"><a href="introduction-to-the-sf-package.html#cb101-4" tabindex="-1"></a>        germany <span class="sc">|&gt;</span> </span>
<span id="cb101-5"><a href="introduction-to-the-sf-package.html#cb101-5" tabindex="-1"></a>        dplyr<span class="sc">::</span><span class="fu">arrange</span>(area) <span class="sc">|&gt;</span> </span>
<span id="cb101-6"><a href="introduction-to-the-sf-package.html#cb101-6" tabindex="-1"></a>        dplyr<span class="sc">::</span><span class="fu">slice_head</span>(<span class="at">n =</span> <span class="dv">10</span>) <span class="sc">|&gt;</span> </span>
<span id="cb101-7"><a href="introduction-to-the-sf-package.html#cb101-7" tabindex="-1"></a>        sf<span class="sc">::</span><span class="fu">st_distance</span>() <span class="sc">|&gt;</span> </span>
<span id="cb101-8"><a href="introduction-to-the-sf-package.html#cb101-8" tabindex="-1"></a>        units<span class="sc">::</span><span class="fu">drop_units</span>() <span class="sc">|&gt;</span> </span>
<span id="cb101-9"><a href="introduction-to-the-sf-package.html#cb101-9" tabindex="-1"></a>        {\(x) x[<span class="fu">upper.tri</span>(x)]}()</span></code></pre></div>
<p>With <code>upper.tri()</code> I select the upper triangle of the matrix (see figure below) so I don’t have every value twice. This also removes the diagonal.
<img src="images/upper-triangular-matrix.png" alt="Upper triangle of a matrix" /></p>
<p>For <code>small10</code> we do the same, but this time with pipe operators. The only differences here are that <code>slice_tail()</code> has been replaced by <code>slice_head()</code> and the annonymous function at the end of the pipe. Anonymous functions are functions without a name. They are not stored as objects but executed directly. In R since version 4.1 we can create anonymous functions as follows:</p>
<div class="sourceCode" id="cb102"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb102-1"><a href="introduction-to-the-sf-package.html#cb102-1" tabindex="-1"></a><span class="co"># The two functions do the same thing. </span></span>
<span id="cb102-2"><a href="introduction-to-the-sf-package.html#cb102-2" tabindex="-1"></a>plus5 <span class="ot">&lt;-</span> <span class="cf">function</span>(x) <span class="fu">return</span>(x<span class="sc">+</span><span class="dv">5</span>)</span>
<span id="cb102-3"><a href="introduction-to-the-sf-package.html#cb102-3" tabindex="-1"></a><span class="fu">plus5</span>(<span class="dv">4</span>)</span></code></pre></div>
<pre><code>## [1] 9</code></pre>
<div class="sourceCode" id="cb104"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb104-1"><a href="introduction-to-the-sf-package.html#cb104-1" tabindex="-1"></a><span class="dv">4</span> <span class="sc">|&gt;</span> {\(x) x <span class="sc">+</span> <span class="dv">5</span>}()</span></code></pre></div>
<pre><code>## [1] 9</code></pre>
<p>Now we still need to package the results in a data set and display them. For the latter, we use the <code>ggplot2</code> package <span class="citation">(<a href="#ref-Wickham2016">Wickham 2016</a>)</span> here. See <a href="https://stats.oarc.ucla.edu/stat/data/intro_ggplot2_int/ggplot2_intro_interactive_flat.html">here</a> for an introduction.</p>
<div class="sourceCode" id="cb106"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb106-1"><a href="introduction-to-the-sf-package.html#cb106-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb106-2"><a href="introduction-to-the-sf-package.html#cb106-2" tabindex="-1"></a></span>
<span id="cb106-3"><a href="introduction-to-the-sf-package.html#cb106-3" tabindex="-1"></a>data <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">size =</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">&quot;big&quot;</span>, <span class="st">&quot;small&quot;</span>), <span class="at">each =</span> <span class="dv">45</span>),</span>
<span id="cb106-4"><a href="introduction-to-the-sf-package.html#cb106-4" tabindex="-1"></a>                   <span class="at">distance =</span> <span class="fu">c</span>(big10, small10))</span>
<span id="cb106-5"><a href="introduction-to-the-sf-package.html#cb106-5" tabindex="-1"></a></span>
<span id="cb106-6"><a href="introduction-to-the-sf-package.html#cb106-6" tabindex="-1"></a><span class="fu">ggplot</span>(data, <span class="fu">aes</span>(<span class="at">y =</span> distance, <span class="at">x =</span> size)) <span class="sc">+</span> <span class="fu">geom_boxplot</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-64-1.png" width="672" />
<br/></p>
<p>So we see that the median distance between the ten largest counties is slightly smaller than that between the ten smallest.</p>
<p>If we have two data sets and we only want to compare the first element of data set 1 with the first of data set 2, the second with the second, and so on, we set the argument <code>by_element</code> to <code>TRUE</code> in the function <code>st_distance()</code>.</p>
<p><br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.15</strong></p>
</div>
<p>Compute the distance between the district Landau in der Pfalz and Berlin (the variable is NAME_3)</p>
</div>
<p><br/></p>
</div>
<div id="st_nearest_feature" class="section level3 hasAnchor" number="1.5.2">
<h3><span class="header-section-number">1.5.2</span> <code>st_nearest_feature</code><a href="introduction-to-the-sf-package.html#st_nearest_feature" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>With <code>st_nearest_feature()</code> we find the elements in a dataset that are closest to the selected element.</p>
<div class="sourceCode" id="cb107"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb107-1"><a href="introduction-to-the-sf-package.html#cb107-1" tabindex="-1"></a><span class="co"># - Select the largest district</span></span>
<span id="cb107-2"><a href="introduction-to-the-sf-package.html#cb107-2" tabindex="-1"></a>big1 <span class="ot">&lt;-</span> germany <span class="sc">|&gt;</span> </span>
<span id="cb107-3"><a href="introduction-to-the-sf-package.html#cb107-3" tabindex="-1"></a>        dplyr<span class="sc">::</span><span class="fu">arrange</span>(area) <span class="sc">|&gt;</span> </span>
<span id="cb107-4"><a href="introduction-to-the-sf-package.html#cb107-4" tabindex="-1"></a>        dplyr<span class="sc">::</span><span class="fu">slice_tail</span>(<span class="at">n =</span> <span class="dv">1</span>)</span>
<span id="cb107-5"><a href="introduction-to-the-sf-package.html#cb107-5" tabindex="-1"></a></span>
<span id="cb107-6"><a href="introduction-to-the-sf-package.html#cb107-6" tabindex="-1"></a><span class="co"># - Which element from germany is closest to the largest district? </span></span>
<span id="cb107-7"><a href="introduction-to-the-sf-package.html#cb107-7" tabindex="-1"></a>nnid <span class="ot">&lt;-</span> <span class="fu">st_nearest_feature</span>(big1, germany)</span>
<span id="cb107-8"><a href="introduction-to-the-sf-package.html#cb107-8" tabindex="-1"></a><span class="co"># - The result is the row number of this closest object. </span></span>
<span id="cb107-9"><a href="introduction-to-the-sf-package.html#cb107-9" tabindex="-1"></a>nnid</span></code></pre></div>
<pre><code>## [1] 2167</code></pre>
<div class="sourceCode" id="cb109"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb109-1"><a href="introduction-to-the-sf-package.html#cb109-1" tabindex="-1"></a>germany[nnid, ]</span></code></pre></div>
<pre><code>## Simple feature collection with 1 feature and 17 fields
## Geometry type: MULTIPOLYGON
## Dimension:     XY
## Bounding box:  xmin: 13.15783 ymin: 52.39318 xmax: 13.24984 ymax: 52.4208
## Geodetic CRS:  WGS 84
##      GID_0  NAME_0   GID_1      NAME_1 NL_NAME_1      GID_2             NAME_2 NL_NAME_2        GID_3       NAME_3 VARNAME_3 NL_NAME_3             TYPE_3    ENGTYPE_3      CC_3 HASC_3
## 2167   DEU Germany DEU.4_1 Brandenburg      &lt;NA&gt; DEU.4.13_1 Potsdam-Mittelmark      &lt;NA&gt; DEU.4.13.6_1 Kleinmachnow      &lt;NA&gt;      &lt;NA&gt; Amtsfreie Gemeinde Municipality 120690304   &lt;NA&gt;
##                                geom     area
## 2167 MULTIPOLYGON (((13.23662 52... 11759803</code></pre>
<div class="sourceCode" id="cb111"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb111-1"><a href="introduction-to-the-sf-package.html#cb111-1" tabindex="-1"></a><span class="fu">tm_shape</span>(<span class="fu">rbind</span>(big1,germany[nnid, ]), <span class="at">zcol =</span> <span class="st">&quot;GID_3&quot;</span>) <span class="sc">+</span> <span class="fu">tm_polygons</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-65-1.png" width="672" /></p>
<p><br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.16</strong></p>
</div>
<p>What is the district closest to Landau in der Pfalz?</p>
</div>
<p><br/></p>
</div>
<div id="spatial-subsetting" class="section level3 hasAnchor" number="1.5.3">
<h3><span class="header-section-number">1.5.3</span> spatial subsetting<a href="introduction-to-the-sf-package.html#spatial-subsetting" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>There are many ways to subset tables in R, using <code>[</code>, <code>select()</code> and <code>filter()</code>.
They use the position of the desired objects in the table (for <code>[</code>), their column names (for <code>select()</code>), or values of the various variables (for <code>filter()</code>).
With spatial data, we can spatial relationships to subset data sets.
The syntax follows the following scheme: Let <code>X</code> be the data set we want to select from and let <code>Y</code> be the data set we want to select with.
For example: we have a set of bird observations all over Germany (<code>X</code>) and a data set with counties (<code>Y</code>) and we want to subset to the birds within one specific county.
Now we subset <code>X</code> by <code>Y</code> by <code>X[Y]</code>.
As an example, we use a set of bird observations (<a href="https://seafile.rlp.net/d/c757bff20f1f49f99cb2/">here</a> for download).
In the code below, you can also see how to turn a data frame into an sf object.
We use the <code>st_as_sf()</code> and provide it with the data frame, the names of the columns that have the coordinates (<code>coords</code>, first x then y), and the CRS.</p>
<div class="sourceCode" id="cb112"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb112-1"><a href="introduction-to-the-sf-package.html#cb112-1" tabindex="-1"></a><span class="co"># - load data</span></span>
<span id="cb112-2"><a href="introduction-to-the-sf-package.html#cb112-2" tabindex="-1"></a>birds <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">&quot;data/birds.rds&quot;</span>)</span>
<span id="cb112-3"><a href="introduction-to-the-sf-package.html#cb112-3" tabindex="-1"></a><span class="co"># - drop observations without spatial coordinates </span></span>
<span id="cb112-4"><a href="introduction-to-the-sf-package.html#cb112-4" tabindex="-1"></a>birds <span class="ot">&lt;-</span> birds[<span class="fu">which</span>(<span class="sc">!</span><span class="fu">is.na</span>(birds<span class="sc">$</span>decimalLongitude)), ]</span>
<span id="cb112-5"><a href="introduction-to-the-sf-package.html#cb112-5" tabindex="-1"></a><span class="co"># - turn bird data into sf object.</span></span>
<span id="cb112-6"><a href="introduction-to-the-sf-package.html#cb112-6" tabindex="-1"></a>birds <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(birds, <span class="at">coords =</span> <span class="fu">c</span>(<span class="st">&quot;decimalLongitude&quot;</span>, <span class="st">&quot;decimalLatitude&quot;</span>), <span class="at">crs =</span> <span class="st">&quot;EPSG:4326&quot;</span>)</span>
<span id="cb112-7"><a href="introduction-to-the-sf-package.html#cb112-7" tabindex="-1"></a><span class="co"># - subset data for plot </span></span>
<span id="cb112-8"><a href="introduction-to-the-sf-package.html#cb112-8" tabindex="-1"></a>birds_subset <span class="ot">&lt;-</span> birds[<span class="dv">1</span><span class="sc">:</span><span class="dv">100</span>, ]</span>
<span id="cb112-9"><a href="introduction-to-the-sf-package.html#cb112-9" tabindex="-1"></a><span class="fu">tm_shape</span>(birds_subset) <span class="sc">+</span> <span class="fu">tm_dots</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-66-1.png" width="672" /></p>
<p>Now we want to select only the bird observations that are located in our county.
The column <code>NAME_2</code> holds the county name.
We select the county <em>Goslar</em>.
Then we subset <code>birds</code> with <code>goslar</code>.</p>
<div class="sourceCode" id="cb113"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb113-1"><a href="introduction-to-the-sf-package.html#cb113-1" tabindex="-1"></a>goslar <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(germany, NAME_2 <span class="sc">==</span> <span class="st">&quot;Goslar&quot;</span>)</span>
<span id="cb113-2"><a href="introduction-to-the-sf-package.html#cb113-2" tabindex="-1"></a>goslar_birds <span class="ot">&lt;-</span> birds[goslar, ]</span>
<span id="cb113-3"><a href="introduction-to-the-sf-package.html#cb113-3" tabindex="-1"></a><span class="fu">tm_shape</span>(goslar_birds) <span class="sc">+</span> <span class="fu">tm_dots</span>()</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-67-1.png" width="672" />
<br/></p>
<p>The subsetting checks for a <em>topological relationship</em> between the elements of <code>birds</code> and <code>goslar</code>.
If, as in the command above, we do not explicitly choose a topological relationship, the default relationship, intersection (per <code>st_intersects()</code>), is applied.
Alternatives are touching the objects (<code>st_touch()</code>), crossing the objects (<code>st_cross()</code>), and covering (<code>st_covers()</code>). See the following figure for more examples.</p>
<div class="float">
<img src="images/topoloical_relations.png" alt="Topological Relationships (Lovelace et al. 2021)" />
<div class="figcaption">Topological Relationships (Lovelace et al. 2021)</div>
</div>
<p>We consider here another example to demonstrate a different topological relationship.
In this example, we use the <code>germany</code> data set and the largest county from the data set (<code>big1</code>).
We want to select all counties that are adjacent to the largest county.
So we subset <code>germany</code> the data set containing all counties using <code>big1</code>, the data set containing only the largest county.
Instead of the <code>st_intersects()</code> relation, which is set by default, we choose <code>st_touches()</code>.</p>
<div class="sourceCode" id="cb114"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb114-1"><a href="introduction-to-the-sf-package.html#cb114-1" tabindex="-1"></a>big1_neighbour <span class="ot">&lt;-</span> germany[big1, op <span class="ot">=</span> st_touches]</span>
<span id="cb114-2"><a href="introduction-to-the-sf-package.html#cb114-2" tabindex="-1"></a><span class="fu">tm_shape</span>(big1_neighbour) <span class="sc">+</span> <span class="fu">tm_polygons</span>(<span class="at">col =</span> <span class="st">&quot;GID_3&quot;</span>, <span class="at">legend.show =</span> F)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-68-1.png" width="672" />
<br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.17</strong></p>
</div>
<p>Select the birds within Berlin, Hannover, and Kiel</p>
</div>
<p><br/></p>
</div>
<div id="spatial-joins" class="section level3 hasAnchor" number="1.5.4">
<h3><span class="header-section-number">1.5.4</span> spatial joins<a href="introduction-to-the-sf-package.html#spatial-joins" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>In a spatial join, we add the variables of a second data set to those of a first one. The spatial relationship between the elements of the objects is used to determine which elements are combined.
An example would be to add the county to the bird data as a variable.</p>
<div class="sourceCode" id="cb115"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb115-1"><a href="introduction-to-the-sf-package.html#cb115-1" tabindex="-1"></a><span class="co"># - Random subset of 500 titmice</span></span>
<span id="cb115-2"><a href="introduction-to-the-sf-package.html#cb115-2" tabindex="-1"></a>birds_subset <span class="ot">&lt;-</span> birds[<span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(birds), <span class="dv">500</span>), ]</span>
<span id="cb115-3"><a href="introduction-to-the-sf-package.html#cb115-3" tabindex="-1"></a></span>
<span id="cb115-4"><a href="introduction-to-the-sf-package.html#cb115-4" tabindex="-1"></a><span class="co"># - create a dataset based on germany but with only one variable: name_2</span></span>
<span id="cb115-5"><a href="introduction-to-the-sf-package.html#cb115-5" tabindex="-1"></a>germany_name2 <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">select</span>(germany, NAME_2)</span>
<span id="cb115-6"><a href="introduction-to-the-sf-package.html#cb115-6" tabindex="-1"></a></span>
<span id="cb115-7"><a href="introduction-to-the-sf-package.html#cb115-7" tabindex="-1"></a><span class="co"># - spatial join </span></span>
<span id="cb115-8"><a href="introduction-to-the-sf-package.html#cb115-8" tabindex="-1"></a>birds_name2 <span class="ot">&lt;-</span> <span class="fu">st_join</span>(birds_subset, germany_name2)</span>
<span id="cb115-9"><a href="introduction-to-the-sf-package.html#cb115-9" tabindex="-1"></a><span class="fu">tm_shape</span>(birds_name2) <span class="sc">+</span> <span class="fu">tm_dots</span>(<span class="at">col =</span> <span class="st">&quot;NAME_2&quot;</span>, <span class="at">legend.show =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>## Warning: Number of levels of the variable &quot;NAME_2&quot; is 198, which is larger than max.categories (which is 30), so levels are combined. Set tmap_options(max.categories = 198) in the
## layer function to show all levels.</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-69-1.png" width="672" /></p>
<p><br/></p>
<div class="blackbox">
<div class="center">
<p><strong>Exercise 1.18</strong></p>
</div>
<ul>
<li>Add the NAME_3 Variable from germany to natura2000 with a spatial join.<br />
</li>
</ul>
</div>
<p><br/></p>
</div>
<div id="spatial-sggregation" class="section level3 hasAnchor" number="1.5.5">
<h3><span class="header-section-number">1.5.5</span> spatial sggregation<a href="introduction-to-the-sf-package.html#spatial-sggregation" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The last thing we want to look at is how we aggregate data.
The question here might be: What is the mean abundance of birds in the different counties.
So we want to:<br />
1. group the bird data according to which district they fall into.<br />
2. calculate for each group the mean value of the abundance (individualCount).<br />
3. assign these mean values to the counties in a data set.</p>
<p>We can do all this with a single function: <code>aggregate()</code>.
However, we need to prepare the data a bit for this.
<code>aggregate()</code> needs the following arguments: <code>x</code> which data should I aggregate? In our case it is the birds.
<code>by</code> in which data are the groups in which I should aggregate? For us it is <code>germany</code>. <code>FUN</code> with which function should I aggregate the data? For us <code>mean()</code>, the mean value.
If you want to give arguments to the function you use to aggregate you can do that afterward.</p>
<div class="sourceCode" id="cb117"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb117-1"><a href="introduction-to-the-sf-package.html#cb117-1" tabindex="-1"></a><span class="co"># - Create a data set where the tits have only the variable individualCount. </span></span>
<span id="cb117-2"><a href="introduction-to-the-sf-package.html#cb117-2" tabindex="-1"></a>birds_count <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">select</span>(birds, individualCount)</span>
<span id="cb117-3"><a href="introduction-to-the-sf-package.html#cb117-3" tabindex="-1"></a><span class="co"># - Reduce to rows that have information for the variable individualCount. </span></span>
<span id="cb117-4"><a href="introduction-to-the-sf-package.html#cb117-4" tabindex="-1"></a>birds_count <span class="ot">&lt;-</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(birds_count, <span class="sc">!</span><span class="fu">is.na</span>(individualCount))</span>
<span id="cb117-5"><a href="introduction-to-the-sf-package.html#cb117-5" tabindex="-1"></a><span class="co"># - aggregate the data birds_count using germany with the function mean. </span></span>
<span id="cb117-6"><a href="introduction-to-the-sf-package.html#cb117-6" tabindex="-1"></a>birds_agg <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(<span class="at">x =</span> birds_count, <span class="at">by =</span> germany, <span class="at">FUN =</span> mean)</span>
<span id="cb117-7"><a href="introduction-to-the-sf-package.html#cb117-7" tabindex="-1"></a><span class="co"># - If we didn&#39;t remove the NAs we could use the following function: </span></span>
<span id="cb117-8"><a href="introduction-to-the-sf-package.html#cb117-8" tabindex="-1"></a>birds_agg <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(<span class="at">x =</span> birds_count, <span class="at">by =</span> germany, <span class="at">FUN =</span> mean, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span>
<span id="cb117-9"><a href="introduction-to-the-sf-package.html#cb117-9" tabindex="-1"></a><span class="co"># - The argument na.rm = TRUE is an argument of the function mean(). It removes (remove, rm) all NAs before calculating the mean. If you open the help page of aggregate() you will see &quot;...&quot; at the arguments. These so called ellipsis are placeholders for all arguments you can give to the function in FUN.  </span></span>
<span id="cb117-10"><a href="introduction-to-the-sf-package.html#cb117-10" tabindex="-1"></a><span class="fu">tm_shape</span>(birds_agg) <span class="sc">+</span> <span class="fu">tm_fill</span>(<span class="at">col =</span> <span class="st">&quot;individualCount&quot;</span>) <span class="sc">+</span> <span class="fu">tm_layout</span>(<span class="at">legend.outside =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-70-1.png" width="672" /></p>

</div>
</div>
</div>
<h3> References<a href="references.html#references" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div id="refs" class="references csl-bib-body hanging-indent" entry-spacing="0">
<div id="ref-Lovelace2019" class="csl-entry">
Lovelace, Robin, Jakub Nowosad, and Jannes Muenchow. 2019. <em>Geocomputation with r</em>. CRC Press.
</div>
<div id="ref-pebesmaSimpleFeaturesStandardized2018" class="csl-entry">
Pebesma, Edzer. 2018. <span>“Simple <span>Features</span> for <span>R</span>: <span>Standardized Support</span> for <span>Spatial Vector Data</span>.”</span> <em>The R Journal</em> 10 (1): 439. <a href="https://doi.org/10.32614/RJ-2018-009">https://doi.org/10.32614/RJ-2018-009</a>.
</div>
<div id="ref-Pebesma2022" class="csl-entry">
Pebesma, Edzer, and Roger Bivand. 2022. <em>Spatial Data Sciencewith Applications in r</em>. <a href="https://r-spatial.org/book/">https://r-spatial.org/book/</a>.
</div>
<div id="ref-Pebesma2016" class="csl-entry">
Pebesma, Edzer, Thomas Mailund, and James Hiebert. 2016. <span>“Measurement Units in <span>R</span>.”</span> <em>R Journal</em> 8 (2): 486–94. <a href="https://doi.org/10.32614/RJ-2016-061">https://doi.org/10.32614/RJ-2016-061</a>.
</div>
<div id="ref-Tennekes2018" class="csl-entry">
Tennekes, Martijn. 2018. <span>“<span class="nocase">tmap</span>: Thematic Maps in <span>R</span>.”</span> <em>Journal of Statistical Software</em> 84 (6): 1–39. <a href="https://doi.org/10.18637/jss.v084.i06">https://doi.org/10.18637/jss.v084.i06</a>.
</div>
<div id="ref-Wickham2016" class="csl-entry">
Wickham, Hadley. 2016. <em>Ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York. <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>.
</div>
<div id="ref-Wickham2022" class="csl-entry">
Wickham, Hadley, Romain François, Lionel Henry, and Kirill Müller. 2022. <em>Dplyr: A Grammar of Data Manipulation</em>. <a href="https://CRAN.R-project.org/package=dplyr">https://CRAN.R-project.org/package=dplyr</a>.
</div>
</div>
            </section>

          </div>
        </div>
      </div>

<a href="rasters-in-r-the-terra-package.html" class="navigation navigation-next navigation-unique" aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/USERNAME/REPO/edit/BRANCH/01-intro-to-sf.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["_main.pdf", "_main.epub"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
